package com.xiaoju

/**
 * Created by cenyuhai on 2015/8/28.
 */
object SfOrderSchema {
  var schema =
    """create_date INTEGER not null,
      |        order_id bigint(20) not null,
      |        order_type INTEGER,
      |        pid bigint(20),
      |        city_id bigint(20),
      |        timeout bigint(20),
      |        p_phone_num varchar(20),
      |        p_create_time varchar,
      |        p_setup_time varchar,
      |        p_ip varchar(100),
      |        p_imei varchar(50) ,
      |        p_suuid varchar(100) ,
      |        p_alipay_zhenshen varchar(128) ,
      |        p_alipay_account varchar(128) ,
      |        p_weixin_openid varchar(128) ,
      |        p_weixin_zhenshen varchar(128) ,
      |        p_order_channel bigint(20),
      |        p_datatype INTEGER,
      |        p_networktype varchar(100) ,
      |        p_pay_total bigint(20),
      |        p_pay_fee bigint(20),
      |        p_pay_time varchar,
      |        p_pay_type INTEGER,
      |        p_pay_ip varchar(100) ,
      |        p_pay_datatype INTEGER,
      |        p_pay_networktype varchar(100),
      |        p_pay_alipay_zhenshen varchar(128) ,
      |        p_pay_alipay_account varchar(128) ,
      |        p_pay_weixin_openid varchar(128) ,
      |        p_pay_weixin_zhenshen varchar(128) ,
      |        p_coupon_id bigint(20),
      |        p_coupon_trackid bigint(20),
      |        p_coupon_amount bigint(20),
      |        is_timeout INTEGER,
      |        did bigint(20),
      |        d_phone_num varchar(20) ,
      |        d_route_id INTEGER,
      |        d_alipay_zhenshen varchar(128) ,
      |        d_alipay_account varchar(128) ,
      |        d_weixin_zhenshen varchar(128) ,
      |        d_weixin_openid varchar(128) ,
      |        d_grab_time varchar,
      |        d_order_channel bigint(20),
      |        d_datatype INTEGER,
      |        d_networktype varchar(100) ,
      |        d_imei varchar(50) ,
      |        d_ip varchar(100) ,
      |        d_suuid varchar(100) ,
      |        d_arrived_ip varchar(50) ,
      |        d_arrived_datatype INTEGER,
      |        d_arrived_networktype varchar(100) ,
      |        d_arrived_time varchar,
      |        order_status INTEGER,
      |        cancel_time varchar,
      |        contact_type INTEGER,
      |        promoter INTEGER,
      |        contact_time varchar,
      |        complain_type INTEGER,
      |        complain_time varchar,
      |        remark varchar(500) ,
      |        var1 INTEGER,
      |        var2 varchar(50) ,
      |        create_time varchar,
      |        update_time varchar,
      |        last_edit_time varchar""".stripMargin
}
