package com.xiaoju

/**
 * Created by cenyuhai on 2015/8/18.
 */
object TableSchema {
  val insertBiTagSql =
    """
      |insert into tmp_dm_tag_pass_dd_kd_merge(
      |phone	,
      |dd_reg_time	,
      |kd_reg_time	,
      |type	,
      |district_id	,
      |city_id	,
      |cid	,
      |model	,
      |sex	,
      |appversion	,
      |os	,
      |osversion	,
      |warn_num	,
      |cnt_badorder	,
      |cnt_forbiden	,
      |channel	,
      |status	,
      |flag_uber	,
      |flag_dita	,
      |flag_tiantian	,
      |flag_51	,
      |flag_weiwei	,
      |score_available	,
      |exchange_time	,
      |value	,
      |current_status	,
      |previous_status	,
      |hb_exp	,
      |home_lng	,
      |home_lat	,
      |home	,
      |home_confidence	,
      |company_lng	,
      |company_lat	,
      |company	,
      |company_confidence	,
      |residence_lng	,
      |residence_lat	,
      |residence	,
      |residence_confidence	,
      |app_interest_code	,
      |game_interest_code	,
      |app_id	,
      |game_id	,
      |last_open_app_time	,
      |dd_date_tot_first_call	,
      |dd_date_tot_last_call	,
      |dd_date_dc_first_call	,
      |dd_date_dc_last_call	,
      |dd_date_zc_first_call	,
      |dd_date_zc_last_call	,
      |dd_date_kc_first_call	,
      |dd_date_kc_last_call	,
      |kd_date_tot_first_call	,
      |kd_date_tot_last_call	,
      |kd_date_dc_first_call	,
      |kd_date_dc_last_call	,
      |kd_date_zc_first_call	,
      |kd_date_zc_last_call	,
      |kd_date_kc_first_call	,
      |kd_date_kc_last_call	,
      |kd_has_zc_call	,
      |kd_has_kc_call	,
      |kd_has_dc_call	,
      |kd_has_tot_call	,
      |dd_has_tot_call	,
      |dd_has_zc_call	,
      |dd_has_kc_call	,
      |dd_has_dc_call	,
      |kd_days_kc_call_silence	,
      |kd_days_zc_call_silence	,
      |kd_days_dc_call_silence	,
      |kd_days_tot_call_silenc	,
      |dd_days_tot_call_silence	,
      |dd_days_dc_call_silence	,
      |dd_days_zc_call_silence	,
      |dd_days_kc_call_silence	,
      |dd_days_qy_call_silence	,
      |dd_has_qy_call	,
      |dd_has_tot_succ	,
      |dd_has_dc_succ	,
      |dd_has_zc_succ	,
      |dd_has_kc_succ	,
      |kd_has_tot_succ	,
      |kd_has_dc_succ	,
      |kd_has_zc_succ	,
      |kd_has_kc_succ	,
      |dd_has_qy_succ	,
      |dd_cnt_ord_call_01_d	,
      |dd_cnt_ord_call_02_d	,
      |dd_cnt_ord_call_03_d	,
      |dd_cnt_ord_call_04_d	,
      |dd_cnt_ord_call_05_d	,
      |dd_cnt_ord_call_06_d	,
      |dd_cnt_ord_call_07_d	,
      |dd_cnt_ord_call_01_w	,
      |dd_cnt_ord_call_02_w	,
      |dd_cnt_ord_call_03_w	,
      |dd_cnt_ord_call_04_w	,
      |dd_cnt_ord_call_01_m	,
      |dd_cnt_ord_call_02_m	,
      |dd_cnt_ord_call_03_m	,
      |dd_cnt_ord_call_04_m	,
      |dd_cnt_ord_call_05_m	,
      |dd_cnt_ord_call_06_m	,
      |dd_cnt_zc_call_01_d	,
      |dd_cnt_zc_call_02_d	,
      |dd_cnt_zc_call_03_d	,
      |dd_cnt_zc_call_04_d	,
      |dd_cnt_zc_call_05_d	,
      |dd_cnt_zc_call_06_d	,
      |dd_cnt_zc_call_07_d	,
      |dd_cnt_kc_call_01_d	,
      |dd_cnt_kc_call_02_d	,
      |dd_cnt_kc_call_03_d	,
      |dd_cnt_kc_call_04_d	,
      |dd_cnt_kc_call_05_d	,
      |dd_cnt_kc_call_06_d	,
      |dd_cnt_kc_call_07_d	,
      |kd_cnt_zc_call_ord_01_d	,
      |kd_cnt_zc_call_ord_02_d	,
      |kd_cnt_zc_call_ord_03_d	,
      |kd_cnt_zc_call_ord_04_d	,
      |kd_cnt_zc_call_ord_05_d	,
      |kd_cnt_zc_call_ord_06_d	,
      |kd_cnt_zc_call_ord_07_d	,
      |kd_cnt_kc_call_ord_01_d	,
      |kd_cnt_kc_call_ord_02_d	,
      |kd_cnt_kc_call_ord_03_d	,
      |kd_cnt_kc_call_ord_04_d	,
      |kd_cnt_kc_call_ord_05_d	,
      |kd_cnt_kc_call_ord_06_d	,
      |kd_cnt_kc_call_ord_07_d	,
      |kd_cnt_taxi_call_ord_01_d	,
      |kd_cnt_taxi_call_ord_02_d	,
      |kd_cnt_taxi_call_ord_03_d	,
      |kd_cnt_taxi_call_ord_04_d	,
      |kd_cnt_taxi_call_ord_05_d	,
      |kd_cnt_taxi_call_ord_06_d	,
      |kd_cnt_taxi_call_ord_07_d	,
      |kd_cnt_call_ord_01_d	,
      |kd_cnt_call_ord_02_d	,
      |kd_cnt_call_ord_03_d	,
      |kd_cnt_call_ord_04_d	,
      |kd_cnt_call_ord_05_d	,
      |kd_cnt_call_ord_06_d	,
      |kd_cnt_call_ord_07_d	,
      |kd_cnt_succ_ord_01_d	,
      |kd_cnt_succ_ord_02_d	,
      |kd_cnt_succ_ord_03_d	,
      |kd_cnt_succ_ord_04_d	,
      |kd_cnt_succ_ord_05_d	,
      |kd_cnt_succ_ord_06_d	,
      |kd_cnt_succ_ord_07_d	,
      |dd_cnt_zc_call_01_w	,
      |dd_cnt_zc_call_02_w	,
      |dd_cnt_zc_call_03_w	,
      |dd_cnt_zc_call_04_w	,
      |dd_cnt_kc_call_01_w	,
      |dd_cnt_kc_call_02_w	,
      |dd_cnt_kc_call_03_w	,
      |dd_cnt_kc_call_04_w	,
      |kd_cnt_zc_call_ord_01_w	,
      |kd_cnt_zc_call_ord_02_w	,
      |kd_cnt_zc_call_ord_03_w	,
      |kd_cnt_zc_call_ord_04_w	,
      |kd_cnt_kc_call_ord_01_w	,
      |kd_cnt_kc_call_ord_02_w	,
      |kd_cnt_kc_call_ord_03_w	,
      |kd_cnt_kc_call_ord_04_w	,
      |kd_cnt_taxi_call_ord_01_w	,
      |kd_cnt_taxi_call_ord_02_w	,
      |kd_cnt_taxi_call_ord_03_w	,
      |kd_cnt_taxi_call_ord_04_w	,
      |kd_cnt_call_ord_01_w	,
      |kd_cnt_call_ord_02_w	,
      |kd_cnt_call_ord_03_w	,
      |kd_cnt_call_ord_04_w	,
      |dd_cnt_zc_call_01_m	,
      |dd_cnt_zc_call_02_m	,
      |dd_cnt_zc_call_03_m	,
      |dd_cnt_zc_call_04_m	,
      |dd_cnt_zc_call_05_m	,
      |dd_cnt_zc_call_06_m	,
      |dd_cnt_kc_call_01_m	,
      |dd_cnt_kc_call_02_m	,
      |dd_cnt_kc_call_03_m	,
      |dd_cnt_kc_call_04_m	,
      |dd_cnt_kc_call_05_m	,
      |dd_cnt_kc_call_06_m	,
      |kd_cnt_zc_call_ord_01_m	,
      |kd_cnt_zc_call_ord_02_m	,
      |kd_cnt_zc_call_ord_03_m	,
      |kd_cnt_zc_call_ord_04_m	,
      |kd_cnt_zc_call_ord_05_m	,
      |kd_cnt_zc_call_ord_06_m	,
      |kd_cnt_kc_call_ord_01_m	,
      |kd_cnt_kc_call_ord_02_m	,
      |kd_cnt_kc_call_ord_03_m	,
      |kd_cnt_kc_call_ord_04_m	,
      |kd_cnt_kc_call_ord_05_m	,
      |kd_cnt_kc_call_ord_06_m	,
      |kd_cnt_taxi_call_ord_01_m	,
      |kd_cnt_taxi_call_ord_02_m	,
      |kd_cnt_taxi_call_ord_03_m	,
      |kd_cnt_taxi_call_ord_04_m	,
      |kd_cnt_taxi_call_ord_05_m	,
      |kd_cnt_taxi_call_ord_06_m	,
      |kd_cnt_call_ord_01_m	,
      |kd_cnt_call_ord_02_m	,
      |kd_cnt_call_ord_03_m	,
      |kd_cnt_call_ord_04_m	,
      |kd_cnt_call_ord_05_m	,
      |kd_cnt_call_ord_06_m	,
      |dd_cnt_zc_preferred_call_01_m	,
      |dd_cnt_zc_preferred_call_02_m	,
      |dd_cnt_zc_preferred_call_03_m	,
      |dd_cnt_zc_preferred_call_04_m	,
      |dd_cnt_zc_preferred_call_05_m	,
      |dd_cnt_zc_preferred_call_06_m	,
      |dd_cnt_zc_comfortable_call_01_m	,
      |dd_cnt_zc_comfortable_call_02_m	,
      |dd_cnt_zc_comfortable_call_03_m	,
      |dd_cnt_zc_comfortable_call_04_m	,
      |dd_cnt_zc_comfortable_call_05_m	,
      |dd_cnt_zc_comfortable_call_06_m	,
      |dd_cnt_zc_business_call_01_m	,
      |dd_cnt_zc_business_call_02_m	,
      |dd_cnt_zc_business_call_03_m	,
      |dd_cnt_zc_business_call_04_m	,
      |dd_cnt_zc_business_call_05_m	,
      |dd_cnt_zc_business_call_06_m	,
      |dd_cnt_zc_premium_call_01_m	,
      |dd_cnt_zc_premium_call_02_m	,
      |dd_cnt_zc_premium_call_03_m	,
      |dd_cnt_zc_premium_call_04_m	,
      |dd_cnt_zc_premium_call_05_m	,
      |dd_cnt_zc_premium_call_06_m	,
      |dd_cnt_zc_call_tot	,
      |dd_cnt_zc_preferred_call_tot	,
      |dd_cnt_zc_comfortable_call_tot	,
      |dd_cnt_zc_business_call_tot	,
      |dd_cnt_zc_premium_call_tot	,
      |dd_cnt_kc_call_tot	,
      |kd_cnt_tot_call_ords	,
      |dd_cnt_ord_call_tot	,
      |dd_cnt_ord_succ_01_d	,
      |dd_cnt_ord_succ_02_d	,
      |dd_cnt_ord_succ_03_d	,
      |dd_cnt_ord_succ_04_d	,
      |dd_cnt_ord_succ_05_d	,
      |dd_cnt_ord_succ_06_d	,
      |dd_cnt_ord_succ_07_d	,
      |dd_cnt_zc_succ_call_01_d	,
      |dd_cnt_zc_succ_call_02_d	,
      |dd_cnt_zc_succ_call_03_d	,
      |dd_cnt_zc_succ_call_04_d	,
      |dd_cnt_zc_succ_call_05_d	,
      |dd_cnt_zc_succ_call_06_d	,
      |dd_cnt_zc_succ_call_07_d	,
      |dd_cnt_kc_succ_call_01_d	,
      |dd_cnt_kc_succ_call_02_d	,
      |dd_cnt_kc_succ_call_03_d	,
      |dd_cnt_kc_succ_call_04_d	,
      |dd_cnt_kc_succ_call_05_d	,
      |dd_cnt_kc_succ_call_06_d	,
      |dd_cnt_kc_succ_call_07_d	,
      |kd_cnt_zc_succ_ord_01_d	,
      |kd_cnt_zc_succ_ord_02_d	,
      |kd_cnt_zc_succ_ord_03_d	,
      |kd_cnt_zc_succ_ord_04_d	,
      |kd_cnt_zc_succ_ord_05_d	,
      |kd_cnt_zc_succ_ord_06_d	,
      |kd_cnt_zc_succ_ord_07_d	,
      |kd_cnt_kc_succ_ord_01_d	,
      |kd_cnt_kc_succ_ord_02_d	,
      |kd_cnt_kc_succ_ord_03_d	,
      |kd_cnt_kc_succ_ord_04_d	,
      |kd_cnt_kc_succ_ord_05_d	,
      |kd_cnt_kc_succ_ord_06_d	,
      |kd_cnt_kc_succ_ord_07_d	,
      |kd_cnt_taxi_succ_ord_01_d	,
      |kd_cnt_taxi_succ_ord_02_d	,
      |kd_cnt_taxi_succ_ord_03_d	,
      |kd_cnt_taxi_succ_ord_04_d	,
      |kd_cnt_taxi_succ_ord_05_d	,
      |kd_cnt_taxi__succ_ord_06_d	,
      |kd_cnt_taxi__succ_ord_07_d	,
      |dd_cnt_ord_succ_01_w	,
      |dd_cnt_ord_succ_02_w	,
      |dd_cnt_ord_succ_03_w	,
      |dd_cnt_ord_succ_04_w	,
      |dd_cnt_zc_succ_call_01_w	,
      |dd_cnt_zc_succ_call_02_w	,
      |dd_cnt_zc_succ_call_03_w	,
      |dd_cnt_zc_succ_call_04_w	,
      |dd_cnt_kc_succ_call_01_w	,
      |dd_cnt_kc_succ_call_02_w	,
      |dd_cnt_kc_succ_call_03_w	,
      |dd_cnt_kc_succ_call_04_w	,
      |kd_cnt_zc_succ_ord_01_w	,
      |kd_cnt_zc_succ_ord_02_w	,
      |kd_cnt_zc_succ_ord_03_w	,
      |kd_cnt_zc_succ_ord_04_w	,
      |kd_cnt_kc_succ_ord_01_w	,
      |kd_cnt_kc_succ_ord_02_w	,
      |kd_cnt_kc_succ_ord_03_w	,
      |kd_cnt_kc_succ_ord_04_w	,
      |kd_cnt_taxi_succ_ord_01_w	,
      |kd_cnt_taxi_succ_ord_02_w	,
      |kd_cnt_taxi_succ_ord_03_w	,
      |kd_cnt_taxi_succ_ord_04_w	,
      |kd_cnt_succ_ord_01_w	,
      |kd_cnt_succ_ord_02_w	,
      |kd_cnt_succ_ord_03_w	,
      |kd_cnt_succ_ord_04_w	,
      |dd_cnt_ord_succ_01_m	,
      |dd_cnt_ord_succ_02_m	,
      |dd_cnt_ord_succ_03_m	,
      |dd_cnt_ord_succ_04_m	,
      |dd_cnt_ord_succ_05_m	,
      |dd_cnt_ord_succ_06_m	,
      |dd_cnt_ord_succ_tot	,
      |dd_cnt_zc_succ_call_01_m	,
      |dd_cnt_zc_succ_call_02_m	,
      |dd_cnt_zc_succ_call_03_m	,
      |dd_cnt_zc_succ_call_04_m	,
      |dd_cnt_zc_succ_call_05_m	,
      |dd_cnt_zc_succ_call_06_m	,
      |dd_cnt_zc_preferred_succ_ords_01_m	,
      |dd_cnt_zc_preferred_succ_ords_02_m	,
      |dd_cnt_zc_preferred_succ_ords_03_m	,
      |dd_cnt_zc_preferred_succ_ords_04_m	,
      |dd_cnt_zc_preferred_succ_ords_05_m	,
      |dd_cnt_zc_preferred_succ_ords_06_m	,
      |dd_cnt_zc_comfortable_succ_ords_01_m	,
      |dd_cnt_zc_comfortable_succ_ords_02_m	,
      |dd_cnt_zc_comfortable_succ_ords_03_m	,
      |dd_cnt_zc_comfortable_succ_ords_04_m	,
      |dd_cnt_zc_comfortable_succ_ords_05_m	,
      |dd_cnt_zc_comfortable_succ_ords_06_m	,
      |dd_cnt_zc_business_succ_ords_01_m	,
      |dd_cnt_zc_business_succ_ords_02_m	,
      |dd_cnt_zc_business_succ_ords_03_m	,
      |dd_cnt_zc_business_succ_ords_04_m	,
      |dd_cnt_zc_business_succ_ords_05_m	,
      |dd_cnt_zc_business_succ_ords_06_m	,
      |dd_cnt_zc_premium_succ_ords_01_m	,
      |dd_cnt_zc_premium_succ_ords_02_m	,
      |dd_cnt_zc_premium_succ_ords_03_m	,
      |dd_cnt_zc_premium_succ_ords_04_m	,
      |dd_cnt_zc_premium_succ_ords_05_m	,
      |dd_cnt_zc_premium_succ_ords_06_m	,
      |dd_cnt_kc_succ_call_01_m	,
      |dd_cnt_kc_succ_call_02_m	,
      |dd_cnt_kc_succ_call_03_m	,
      |dd_cnt_kc_succ_call_04_m	,
      |dd_cnt_kc_succ_call_05_m	,
      |dd_cnt_kc_succ_call_06_m	,
      |kd_cnt_zc_succ_ord_01_m	,
      |kd_cnt_zc_succ_ord_02_m	,
      |kd_cnt_zc_succ_ord_03_m	,
      |kd_cnt_zc_succ_ord_04_m	,
      |kd_cnt_zc_succ_ord_05_m	,
      |kd_cnt_zc_succ_ord_06_m	,
      |kd_cnt_kc_succ_ord_01_m	,
      |kd_cnt_kc_succ_ord_02_m	,
      |kd_cnt_kc_succ_ord_03_m	,
      |kd_cnt_kc_succ_ord_04_m	,
      |kd_cnt_kc_succ_ord_05_m	,
      |kd_cnt_kc_succ_ord_06_m	,
      |kd_cnt_taxi_succ_ord_01_m	,
      |kd_cnt_taxi_succ_ord_02_m	,
      |kd_cnt_taxi_succ_ord_03_m	,
      |kd_cnt_taxi_succ_ord_04_m	,
      |kd_cnt_taxi_succ_ord_05_m	,
      |kd_cnt_taxi_succ_ord_06_m	,
      |kd_cnt_succ_ord_01_m	,
      |kd_cnt_succ_ord_02_m	,
      |kd_cnt_succ_ord_03_m	,
      |kd_cnt_succ_ord_04_m	,
      |kd_cnt_succ_ord_05_m	,
      |kd_cnt_succ_ord_06_m	,
      |dd_cnt_zc_succ_call_tot	,
      |dd_cnt_zc_preferred_succ_ords_tot	,
      |dd_cnt_zc_comfortable_succ_ords_tot	,
      |dd_cnt_zc_business_succ_ords_tot	,
      |dd_cnt_zc_premium_succ_ords_tot	,
      |dd_cnt_kc_succ_call_tot	,
      |dd_cnt_ord_pass_cacled_tot	,
      |dd_cnt_ord_pass_cacl_tot	,
      |dd_cnt_zc_aft_strive_pcancel_call_tot	,
      |dd_cnt_zc_bef_strive_pcancel_call_tot	,
      |dd_cnt_kc_aft_strive_pcancel_call_tot	,
      |dd_cnt_kc_bef_strive_pcancel_call_tot	,
      |kd_cnt_tot_pass_cancle_ords	,
      |kd_cnt_zc_pass_cancle_ord_01_d	,
      |kd_cnt_zc_pass_cancle_ord_02_d	,
      |kd_cnt_zc_pass_cancle_ord_03_d	,
      |kd_cnt_zc_pass_cancle_ord_04_d	,
      |kd_cnt_zc_pass_cancle_ord_05_d	,
      |kd_cnt_zc_pass_cancle_ord_06_d	,
      |kd_cnt_zc_pass_cancle_ord_07_d	,
      |kd_cnt_kc_pass_cancle_ord_01_d	,
      |kd_cnt_kc_pass_cancle_ord_02_d	,
      |kd_cnt_kc_pass_cancle_ord_03_d	,
      |kd_cnt_kc_pass_cancle_ord_04_d	,
      |kd_cnt_kc_pass_cancle_ord_05_d	,
      |kd_cnt_kc_pass_cancle_ord_06_d	,
      |kd_cnt_kc_pass_cancle_ord_07_d	,
      |kd_cnt_taxi_pass_cancle_ord_01_d	,
      |kd_cnt_taxi_pass_cancle_ord_02_d	,
      |kd_cnt_taxi_pass_cancle_ord_03_d	,
      |kd_cnt_taxi_pass_cancle_ord_04_d	,
      |kd_cnt_taxi_pass_cancle_ord_05_d	,
      |kd_cnt_taxi_pass_cancle_ord_06_d	,
      |kd_cnt_taxi_pass_cancle_ord_07_d	,
      |kd_cnt_pass_cancle_ord_01_d	,
      |kd_cnt_pass_cancle_ord_02_d	,
      |kd_cnt_pass_cancle_ord_03_d	,
      |kd_cnt_pass_cancle_ord_04_d	,
      |kd_cnt_pass_cancle_ord_05_d	,
      |kd_cnt_pass_cancle_ord_06_d	,
      |kd_cnt_pass_cancle_ord_07_d	,
      |kd_cnt_taxi_pass_cancle_ord_01_w	,
      |kd_cnt_taxi_pass_cancle_ord_02_w	,
      |kd_cnt_taxi_pass_cancle_ord_03_w	,
      |kd_cnt_taxi_pass_cancle_ord_04_w	,
      |kd_cnt_pass_cancle_ord_01_w	,
      |kd_cnt_pass_cancle_ord_02_w	,
      |kd_cnt_pass_cancle_ord_03_w	,
      |kd_cnt_pass_cancle_ord_04_w	,
      |kd_cnt_zc_pass_cancle_ord_01_m	,
      |kd_cnt_zc_pass_cancle_ord_02_m	,
      |kd_cnt_zc_pass_cancle_ord_03_m	,
      |kd_cnt_zc_pass_cancle_ord_04_m	,
      |kd_cnt_zc_pass_cancle_ord_05_m	,
      |kd_cnt_zc_pass_cancle_ord_06_m	,
      |kd_cnt_kc_pass_cancle_ord_01_m	,
      |kd_cnt_kc_pass_cancle_ord_02_m	,
      |kd_cnt_kc_pass_cancle_ord_03_m	,
      |kd_cnt_kc_pass_cancle_ord_04_m	,
      |kd_cnt_kc_pass_cancle_ord_05_m	,
      |kd_cnt_kc_pass_cancle_ord_06_m	,
      |kd_cnt_taxi_pass_cancle_ord_01_m	,
      |kd_cnt_taxi_pass_cancle_ord_02_m	,
      |kd_cnt_taxi_pass_cancle_ord_03_m	,
      |kd_cnt_taxi_pass_cancle_ord_04_m	,
      |kd_cnt_taxi_pass_cancle_ord_05_m	,
      |kd_cnt_taxi_pass_cancle_ord_06_m	,
      |kd_cnt_pass_cancle_ord_01_m	,
      |kd_cnt_pass_cancle_ord_02_m	,
      |kd_cnt_pass_cancle_ord_03_m	,
      |kd_cnt_pass_cancle_ord_04_m	,
      |kd_cnt_pass_cancle_ord_05_m	,
      |kd_cnt_pass_cancle_ord_06_m	,
      |dd_cnt_ord_cacl_01_m	,
      |dd_cnt_ord_cacl_02_m	,
      |dd_cnt_ord_cacl_03_m	,
      |dd_cnt_ord_cacl_04_m	,
      |dd_cnt_ord_cacl_05_m	,
      |dd_cnt_ord_cacl_06_m	,
      |dd_cnt_ord_nodeal_01_m	,
      |dd_cnt_ord_nodeal_02_m	,
      |dd_cnt_ord_nodeal_03_m	,
      |dd_cnt_ord_nodeal_04_m	,
      |dd_cnt_ord_nodeal_05_m	,
      |dd_cnt_ord_nodeal_06_m	,
      |dd_cnt_ord_nodeal_tot	,
      |dd_cnt_ord_bonus_lift_5_tot	,
      |dd_cnt_ord_bonus_lift_10_tot	,
      |dd_cnt_ord_bonus_lift_15_tot	,
      |dd_cnt_ord_bonus_lift_20_tot	,
      |dd_cnt_ord_succ_bonus_lift_tot	,
      |dd_cnt_ord_bonus_lift_tot	,
      |dd_cnt_ord_bonus_lift_01_w	,
      |dd_cnt_ord_bonus_lift_02_w	,
      |dd_cnt_ord_bonus_lift_03_w	,
      |dd_cnt_ord_bonus_lift_04_w	,
      |dd_cnt_ord_bonus_lift_01_m	,
      |dd_cnt_ord_bonus_lift_02_m	,
      |dd_cnt_ord_bonus_lift_03_m	,
      |dd_cnt_ord_bonus_lift_04_m	,
      |dd_cnt_ord_bonus_lift_05_m	,
      |dd_cnt_ord_bonus_lift_06_m	,
      |dd_amt_ord_bonus_lift_01_w	,
      |dd_amt_ord_bonus_lift_02_w	,
      |dd_amt_ord_bonus_lift_03_w	,
      |dd_amt_ord_bonus_lift_04_w	,
      |dd_amt_ord_bonus_lift_01_m	,
      |dd_amt_ord_bonus_lift_02_m	,
      |dd_amt_ord_bonus_lift_03_m	,
      |dd_amt_ord_bonus_lift_04_m	,
      |dd_amt_ord_bonus_lift_05_m	,
      |dd_amt_ord_bonus_lift_06_m	,
      |dd_amt_ord_succ_bonus_lift_tot	,
      |dd_amt_ord_bonus_lift_tot	,
      |dd_cnt_rob_succ_days_01_w	,
      |dd_cnt_rob_succ_days_02_w	,
      |dd_cnt_rob_succ_days_03_w	,
      |dd_cnt_rob_succ_days_04_w	,
      |kd_cnt_zc_succ_ord_days_01_w	,
      |kd_cnt_zc_succ_ord_days_02_w	,
      |kd_cnt_zc_succ_ord_days_03_w	,
      |kd_cnt_zc_succ_ord_days_04_w	,
      |kd_cnt_kc_succ_ord_days_01_w	,
      |kd_cnt_kc_succ_ord_days_02_w	,
      |kd_cnt_kc_succ_ord_days_03_w	,
      |kd_cnt_kc_succ_ord_days_04_w	,
      |kd_cnt_taxi_succ_ord_days_01_w	,
      |kd_cnt_taxi_succ_ord_days_02_w	,
      |kd_cnt_taxi_succ_ord_days_03_w	,
      |kd_cnt_taxi_succ_ord_days_04_w	,
      |kd_cnt_succ_ord_days_01_w	,
      |kd_cnt_succ_ord_days_02_w	,
      |kd_cnt_succ_ord_days_03_w	,
      |kd_cnt_succ_ord_days_04_w	,
      |kd_cnt_zc_succ_ord_days_01_m	,
      |kd_cnt_zc_succ_ord_days_02_m	,
      |kd_cnt_zc_succ_ord_days_03_m	,
      |kd_cnt_zc_succ_ord_days_04_m	,
      |kd_cnt_zc_succ_ord_days_05_m	,
      |kd_cnt_zc_succ_ord_days_06_m	,
      |kd_cnt_kc_succ_ord_days_01_m	,
      |kd_cnt_kc_succ_ord_days_02_m	,
      |kd_cnt_kc_succ_ord_days_03_m	,
      |kd_cnt_kc_succ_ord_days_04_m	,
      |kd_cnt_kc_succ_ord_days_05_m	,
      |kd_cnt_kc_succ_ord_days_06_m	,
      |kd_cnt_taxi_succ_ord_days_01_m	,
      |kd_cnt_taxi_succ_ord_days_02_m	,
      |kd_cnt_taxi_succ_ord_days_03_m	,
      |kd_cnt_taxi_succ_ord_days_04_m	,
      |kd_cnt_taxi_succ_ord_days_05_m	,
      |kd_cnt_taxi_succ_ord_days_06_m	,
      |kd_cnt_succ_ord_days_01_m	,
      |kd_cnt_succ_ord_days_02_m	,
      |kd_cnt_succ_ord_days_03_m	,
      |kd_cnt_succ_ord_days_04_m	,
      |kd_cnt_succ_ord_days_05_m	,
      |kd_cnt_succ_ord_days_06_m	,
      |kd_cnt_tot_succ_ord_days	,
      |kd_cnt_tot_call_days	,
      |dd_cnt_call_days_14_d	,
      |dd_cnt_call_days_30_d	,
      |kd_cnt_zc_call_days_01_w	,
      |kd_cnt_zc_call_days_02_w	,
      |kd_cnt_zc_call_days_03_w	,
      |kd_cnt_zc_call_days_04_w	,
      |kd_cnt_kc_call_days_01_w	,
      |kd_cnt_kc_call_days_02_w	,
      |kd_cnt_kc_call_days_03_w	,
      |kd_cnt_kc_call_days_04_w	,
      |kd_cnt_taxi_call_days_01_w	,
      |kd_cnt_taxi_call_days_02_w	,
      |kd_cnt_taxi_call_days_03_w	,
      |kd_cnt_taxi_call_days_04_w	,
      |kd_cnt_call_days_01_w	,
      |kd_cnt_call_days_02_w	,
      |kd_cnt_call_days_03_w	,
      |kd_cnt_call_days_04_w	,
      |kd_cnt_zc_call_days_01_m	,
      |kd_cnt_zc_call_days_02_m	,
      |kd_cnt_zc_call_days_03_m	,
      |kd_cnt_zc_call_days_04_m	,
      |kd_cnt_zc_call_days_05_m	,
      |kd_cnt_zc_call_days_06_m	,
      |kd_cnt_kc_call_days_01_m	,
      |kd_cnt_kc_call_days_02_m	,
      |kd_cnt_kc_call_days_03_m	,
      |kd_cnt_kc_call_days_04_m	,
      |kd_cnt_kc_call_days_05_m	,
      |kd_cnt_kc_call_days_06_m	,
      |kd_cnt_taxi_call_days_01_m	,
      |kd_cnt_taxi_call_days_02_m	,
      |kd_cnt_taxi_call_days_03_m	,
      |kd_cnt_taxi_call_days_04_m	,
      |kd_cnt_taxi_call_days_05_m	,
      |kd_cnt_taxi_call_days_06_m	,
      |kd_cnt_call_days_01_m	,
      |kd_cnt_call_days_02_m	,
      |kd_cnt_call_days_03_m	,
      |kd_cnt_call_days_04_m	,
      |kd_cnt_call_days_05_m	,
      |kd_cnt_call_days_06_m	,
      |dd_secs_zc_strive_01_w	,
      |dd_secs_zc_strive_02_w	,
      |dd_secs_zc_strive_03_w	,
      |dd_secs_zc_strive_04_w	,
      |dd_secs_zc_strive_01_m	,
      |dd_secs_zc_strive_02_m	,
      |dd_secs_zc_strive_03_m	,
      |dd_secs_zc_strive_04_m	,
      |dd_secs_zc_strive_05_m	,
      |dd_secs_zc_strive_06_m	,
      |dd_secs_kc_strive_01_d	,
      |dd_secs_kc_strive_02_d	,
      |dd_secs_kc_strive_03_d	,
      |dd_secs_kc_strive_04_d	,
      |dd_secs_kc_strive_05_d	,
      |dd_secs_kc_strive_06_d	,
      |dd_secs_kc_strive_07_d	,
      |dd_secs_kc_strive_01_w	,
      |dd_secs_kc_strive_02_w	,
      |dd_secs_kc_strive_03_w	,
      |dd_secs_kc_strive_04_w	,
      |dd_secs_kc_strive_01_m	,
      |dd_secs_kc_strive_02_m	,
      |dd_secs_kc_strive_03_m	,
      |dd_secs_kc_strive_04_m	,
      |dd_secs_kc_strive_05_m	,
      |dd_secs_kc_strive_06_m	,
      |dd_secs_kc_strive_tot	,
      |dd_secs_zc_strive_tot	,
      |dd_secs_zc_pwait_01_w	,
      |dd_secs_zc_pwait_02_w	,
      |dd_secs_zc_pwait_03_w	,
      |dd_secs_zc_pwait_04_w	,
      |dd_secs_zc_wwait_01_w	,
      |dd_secs_zc_wwait_02_w	,
      |dd_secs_zc_wwait_03_w	,
      |dd_secs_zc_wwait_04_w	,
      |dd_secs_zc_pwait_01_m	,
      |dd_secs_zc_pwait_02_m	,
      |dd_secs_zc_pwait_03_m	,
      |dd_secs_zc_pwait_04_m	,
      |dd_secs_zc_pwait_05_m	,
      |dd_secs_zc_pwait_06_m	,
      |dd_secs_zc_mwait_01_m	,
      |dd_secs_zc_mwait_02_m	,
      |dd_secs_zc_mwait_03_m	,
      |dd_secs_zc_mwait_04_m	,
      |dd_secs_zc_mwait_05_m	,
      |dd_secs_zc_mwait_06_m	,
      |dd_secs_zc_pwait_tot	,
      |dd_secs_zc_totwait_tot	,
      |dd_secs_kc_pwait_01_m	,
      |dd_secs_kc_pwait_02_m	,
      |dd_secs_kc_pwait_03_m	,
      |dd_secs_kc_pwait_04_m	,
      |dd_secs_kc_pwait_05_m	,
      |dd_secs_kc_pwait_06_m	,
      |dd_secs_kc_mwait_01_m	,
      |dd_secs_kc_mwait_02_m	,
      |dd_secs_kc_mwait_03_m	,
      |dd_secs_kc_mwait_04_m	,
      |dd_secs_kc_mwait_05_m	,
      |dd_secs_kc_mwait_06_m	,
      |dd_secs_kc_pwait_tot	,
      |dd_secs_kc_totwait_tot	,
      |dd_cnt_wx_pay_succ_ord_01_d	,
      |dd_cnt_wx_pay_succ_ord_02_d	,
      |dd_cnt_wx_pay_succ_ord_03_d	,
      |dd_cnt_wx_pay_succ_ord_04_d	,
      |dd_cnt_wx_pay_succ_ord_05_d	,
      |dd_cnt_wx_pay_succ_ord_06_d	,
      |dd_cnt_wx_pay_succ_ord_07_d	,
      |kd_cnt_zc_pay_succ_ord_01_d	,
      |kd_cnt_zc_pay_succ_ord_02_d	,
      |kd_cnt_zc_pay_succ_ord_03_d	,
      |kd_cnt_zc_pay_succ_ord_04_d	,
      |kd_cnt_zc_pay_succ_ord_05_d	,
      |kd_cnt_zc_pay_succ_ord_06_d	,
      |kd_cnt_zc_pay_succ_ord_07_d	,
      |kd_cnt_kc_pay_succ_ord_01_d	,
      |kd_cnt_kc_pay_succ_ord_02_d	,
      |kd_cnt_kc_pay_succ_ord_03_d	,
      |kd_cnt_kc_pay_succ_ord_04_d	,
      |kd_cnt_kc_pay_succ_ord_05_d	,
      |kd_cnt_kc_pay_succ_ord_06_d	,
      |kd_cnt_kc_pay_succ_ord_07_d	,
      |kd_cnt_taxi_pay_succ_ord_01_d	,
      |kd_cnt_taxi_pay_succ_ord_02_d	,
      |kd_cnt_taxi_pay_succ_ord_03_d	,
      |kd_cnt_taxi_pay_succ_ord_04_d	,
      |kd_cnt_taxi_pay_succ_ord_05_d	,
      |kd_cnt_taxi_pay_succ_ord_06_d	,
      |kd_cnt_taxi_pay_succ_ord_07_d	,
      |kd_cnt_pay_succ_ord_01_d	,
      |kd_cnt_pay_succ_ord_02_d	,
      |kd_cnt_pay_succ_ord_03_d	,
      |kd_cnt_pay_succ_ord_04_d	,
      |kd_cnt_pay_succ_ord_05_d	,
      |kd_cnt_pay_succ_ord_06_d	,
      |kd_cnt_pay_succ_ord_07_d	,
      |dd_cnt_wx_pay_succ_ord_01_w	,
      |dd_cnt_wx_pay_succ_ord_02_w	,
      |dd_cnt_wx_pay_succ_ord_03_w	,
      |dd_cnt_wx_pay_succ_ord_04_w	,
      |kd_cnt_zc_pay_succ_ord_01_w	,
      |kd_cnt_zc_pay_succ_ord_02_w	,
      |kd_cnt_zc_pay_succ_ord_03_w	,
      |kd_cnt_zc_pay_succ_ord_04_w	,
      |kd_cnt_kc_pay_succ_ord_01_w	,
      |kd_cnt_kc_pay_succ_ord_02_w	,
      |kd_cnt_kc_pay_succ_ord_03_w	,
      |kd_cnt_kc_pay_succ_ord_04_w	,
      |kd_cnt_taxi_pay_succ_ord_01_w	,
      |kd_cnt_taxi_pay_succ_ord_02_w	,
      |kd_cnt_taxi_pay_succ_ord_03_w	,
      |kd_cnt_taxi_pay_succ_ord_04_w	,
      |kd_cnt_pay_succ_ord_01_w	,
      |kd_cnt_pay_succ_ord_02_w	,
      |kd_cnt_pay_succ_ord_03_w	,
      |kd_cnt_pay_succ_ord_04_w	,
      |dd_cnt_wx_pay_succ_ord_01_m	,
      |dd_cnt_wx_pay_succ_ord_02_m	,
      |dd_cnt_wx_pay_succ_ord_03_m	,
      |dd_cnt_wx_pay_succ_ord_04_m	,
      |dd_cnt_wx_pay_succ_ord_05_m	,
      |dd_cnt_wx_pay_succ_ord_06_m	,
      |kd_cnt_zc_pay_succ_ord_01_m	,
      |kd_cnt_zc_pay_succ_ord_02_m	,
      |kd_cnt_zc_pay_succ_ord_03_m	,
      |kd_cnt_zc_pay_succ_ord_04_m	,
      |kd_cnt_zc_pay_succ_ord_05_m	,
      |kd_cnt_zc_pay_succ_ord_06_m	,
      |kd_cnt_kc_pay_succ_ord_01_m	,
      |kd_cnt_kc_pay_succ_ord_02_m	,
      |kd_cnt_kc_pay_succ_ord_03_m	,
      |kd_cnt_kc_pay_succ_ord_04_m	,
      |kd_cnt_kc_pay_succ_ord_05_m	,
      |kd_cnt_kc_pay_succ_ord_06_m	,
      |kd_cnt_taxi_pay_succ_ord_01_m	,
      |kd_cnt_taxi_pay_succ_ord_02_m	,
      |kd_cnt_taxi_pay_succ_ord_03_m	,
      |kd_cnt_taxi_pay_succ_ord_04_m	,
      |kd_cnt_taxi_pay_succ_ord_05_m	,
      |kd_cnt_taxi_pay_succ_ord_06_m	,
      |kd_cnt_pay_succ_ord_01_m	,
      |kd_cnt_pay_succ_ord_02_m	,
      |kd_cnt_pay_succ_ord_03_m	,
      |kd_cnt_pay_succ_ord_04_m	,
      |kd_cnt_pay_succ_ord_05_m	,
      |kd_cnt_pay_succ_ord_06_m	,
      |dd_cnt_wx_pay_succ_ord_tot	,
      |kd_cnt_tot_pay_succ_ords	,
      |dd_cnt_wx_succ_didi_global	,
      |dd_cnt_ord_pay_fin_tot	,
      |dd_cnt_wx_pay_ord_01_w	,
      |dd_cnt_wx_pay_ord_02_w	,
      |dd_cnt_wx_pay_ord_03_w	,
      |dd_cnt_wx_pay_ord_04_w	,
      |dd_cnt_wx_pay_ord_01_m	,
      |dd_cnt_wx_pay_ord_02_m	,
      |dd_cnt_wx_pay_ord_03_m	,
      |dd_cnt_wx_pay_ord_04_m	,
      |dd_cnt_wx_pay_ord_05_m	,
      |dd_cnt_wx_pay_ord_06_m	,
      |dd_cnt_wx_pay_use_bonus_ord_01_d	,
      |dd_cnt_wx_pay_use_bonus_ord_02_d	,
      |dd_cnt_wx_pay_use_bonus_ord_03_d	,
      |dd_cnt_wx_pay_use_bonus_ord_04_d	,
      |dd_cnt_wx_pay_use_bonus_ord_05_d	,
      |dd_cnt_wx_pay_use_bonus_ord_06_d	,
      |dd_cnt_wx_pay_use_bonus_ord_07_d	,
      |dd_cnt_wx_pay_use_bonus_ord_01_w	,
      |dd_cnt_wx_pay_use_bonus_ord_02_w	,
      |dd_cnt_wx_pay_use_bonus_ord_03_w	,
      |dd_cnt_wx_pay_use_bonus_ord_04_w	,
      |dd_cnt_wx_pay_use_bonus_ord_01_m	,
      |dd_cnt_wx_pay_use_bonus_ord_02_m	,
      |dd_cnt_wx_pay_use_bonus_ord_03_m	,
      |dd_cnt_wx_pay_use_bonus_ord_04_m	,
      |dd_cnt_wx_pay_use_bonus_ord_05_m	,
      |dd_cnt_wx_pay_use_bonus_ord_06_m	,
      |dd_cnt_wx_pay_nouse_bonus_ord_01_w	,
      |dd_cnt_wx_pay_nouse_bonus_ord_02_w	,
      |dd_cnt_wx_pay_nouse_bonus_ord_03_w	,
      |dd_cnt_wx_pay_nouse_bonus_ord_04_w	,
      |dd_cnt_wx_pay_nouse_bonus_ord_01_m	,
      |dd_cnt_wx_pay_nouse_bonus_ord_02_m	,
      |dd_cnt_wx_pay_nouse_bonus_ord_03_m	,
      |dd_cnt_wx_pay_nouse_bonus_ord_04_m	,
      |dd_cnt_wx_pay_nouse_bonus_ord_05_m	,
      |dd_cnt_wx_pay_nouse_bonus_ord_06_m	,
      |dd_cnt_wx_pay_nouse_bonus_ord_01_d	,
      |dd_cnt_wx_pay_nouse_bonus_ord_02_d	,
      |dd_cnt_wx_pay_nouse_bonus_ord_03_d	,
      |dd_cnt_wx_pay_nouse_bonus_ord_04_d	,
      |dd_cnt_wx_pay_nouse_bonus_ord_05_d	,
      |dd_cnt_wx_pay_nouse_bonus_ord_06_d	,
      |dd_cnt_wx_pay_nouse_bonus_ord_07_d	,
      |dd_amt_wx_use_bonus_01_d	,
      |dd_amt_wx_use_bonus_02_d	,
      |dd_amt_wx_use_bonus_03_d	,
      |dd_amt_wx_use_bonus_04_d	,
      |dd_amt_wx_use_bonus_05_d	,
      |dd_amt_wx_use_bonus_06_d	,
      |dd_amt_wx_use_bonus_07_d	,
      |dd_amt_wx_use_bonus_01_w	,
      |dd_amt_wx_use_bonus_02_w	,
      |dd_amt_wx_use_bonus_03_w	,
      |dd_amt_wx_use_bonus_04_w	,
      |dd_amt_wx_use_bonus_01_m	,
      |dd_amt_wx_use_bonus_02_m	,
      |dd_amt_wx_use_bonus_03_m	,
      |dd_amt_wx_use_bonus_04_m	,
      |dd_amt_wx_use_bonus_05_m	,
      |dd_amt_wx_use_bonus_06_m	,
      |dd_amt_wx_succ_pay_01_d	,
      |dd_amt_wx_succ_pay_02_d	,
      |dd_amt_wx_succ_pay_03_d	,
      |dd_amt_wx_succ_pay_04_d	,
      |dd_amt_wx_succ_pay_05_d	,
      |dd_amt_wx_succ_pay_06_d	,
      |dd_amt_wx_succ_pay_07_d	,
      |kd_amt_zc_pay_cost_01_d	,
      |kd_amt_zc_pay_cost_02_d	,
      |kd_amt_zc_pay_cost_03_d	,
      |kd_amt_zc_pay_cost_04_d	,
      |kd_amt_zc_pay_cost_05_d	,
      |kd_amt_zc_pay_cost_06_d	,
      |kd_amt_zc_pay_cost_07_d	,
      |kd_amt_kc_pay_cost_01_d	,
      |kd_amt_kc_pay_cost_02_d	,
      |kd_amt_kc_pay_cost_03_d	,
      |kd_amt_kc_pay_cost_04_d	,
      |kd_amt_kc_pay_cost_05_d	,
      |kd_amt_kc_pay_cost_06_d	,
      |kd_amt_kc_pay_cost_07_d	,
      |kd_amt_taxi_pay_cost_01_d	,
      |kd_amt_taxi_pay_cost_02_d	,
      |kd_amt_taxi_pay_cost_03_d	,
      |kd_amt_taxi_pay_cost_04_d	,
      |kd_amt_taxi_pay_cost_05_d	,
      |kd_amt_taxi_pay_cost_06_d	,
      |kd_amt_taxi_pay_cost_07_d	,
      |kd_amt_pay_cost_01_d	,
      |kd_amt_pay_cost_02_d	,
      |kd_amt_pay_cost_03_d	,
      |kd_amt_pay_cost_04_d	,
      |kd_amt_pay_cost_05_d	,
      |kd_amt_pay_cost_06_d	,
      |kd_amt_pay_cost_07_d	,
      |dd_amt_wx_succ_pay_01_w	,
      |dd_amt_wx_succ_pay_02_w	,
      |dd_amt_wx_succ_pay_03_w	,
      |dd_amt_wx_succ_pay_04_w	,
      |kd_amt_zc_pay_cost_01_w	,
      |kd_amt_zc_pay_cost_02_w	,
      |kd_amt_zc_pay_cost_03_w	,
      |kd_amt_zc_pay_cost_04_w	,
      |kd_amt_kc_pay_cost_01_w	,
      |kd_amt_kc_pay_cost_02_w	,
      |kd_amt_kc_pay_cost_03_w	,
      |kd_amt_kc_pay_cost_04_w	,
      |kd_amt_taxi_pay_cost_01_w	,
      |kd_amt_taxi_pay_cost_02_w	,
      |kd_amt_taxi_pay_cost_03_w	,
      |kd_amt_taxi_pay_cost_04_w	,
      |kd_amt_pay_cost_01_w	,
      |kd_amt_pay_cost_02_w	,
      |kd_amt_pay_cost_03_w	,
      |kd_amt_pay_cost_04_w	,
      |dd_amt_wx_succ_pay_01_m	,
      |dd_amt_wx_succ_pay_02_m	,
      |dd_amt_wx_succ_pay_03_m	,
      |dd_amt_wx_succ_pay_04_m	,
      |dd_amt_wx_succ_pay_05_m	,
      |dd_amt_wx_succ_pay_06_m	,
      |kd_amt_zc_pay_cost_01_m	,
      |kd_amt_zc_pay_cost_02_m	,
      |kd_amt_zc_pay_cost_03_m	,
      |kd_amt_zc_pay_cost_04_m	,
      |kd_amt_zc_pay_cost_05_m	,
      |kd_amt_zc_pay_cost_06_m	,
      |kd_amt_kc_pay_cost_01_m	,
      |kd_amt_kc_pay_cost_02_m	,
      |kd_amt_kc_pay_cost_03_m	,
      |kd_amt_kc_pay_cost_04_m	,
      |kd_amt_kc_pay_cost_05_m	,
      |kd_amt_kc_pay_cost_06_m	,
      |kd_amt_taxi_pay_cost_01_m	,
      |kd_amt_taxi_pay_cost_02_m	,
      |kd_amt_taxi_pay_cost_03_m	,
      |kd_amt_taxi_pay_cost_04_m	,
      |kd_amt_taxi_pay_cost_05_m	,
      |kd_amt_taxi_pay_cost_06_m	,
      |kd_amt_pay_cost_01_m	,
      |kd_amt_pay_cost_02_m	,
      |kd_amt_pay_cost_03_m	,
      |kd_amt_pay_cost_04_m	,
      |kd_amt_pay_cost_05_m	,
      |kd_amt_pay_cost_06_m	,
      |dd_cnt_kc_rd_ords_01_d	,
      |dd_cnt_kc_rd_ords_02_d	,
      |dd_cnt_kc_rd_ords_03_d	,
      |dd_cnt_kc_rd_ords_04_d	,
      |dd_cnt_kc_rd_ords_05_d	,
      |dd_cnt_kc_rd_ords_06_d	,
      |dd_cnt_kc_rd_ords_07_d	,
      |dd_cnt_zc_rd_ords_01_d	,
      |dd_cnt_zc_rd_ords_02_d	,
      |dd_cnt_zc_rd_ords_03_d	,
      |dd_cnt_zc_rd_ords_04_d	,
      |dd_cnt_zc_rd_ords_05_d	,
      |dd_cnt_zc_rd_ords_06_d	,
      |dd_cnt_zc_rd_ords_07_d	,
      |dd_cnt_zc_rd_ords_01_w	,
      |dd_cnt_zc_rd_ords_02_w	,
      |dd_cnt_zc_rd_ords_03_w	,
      |dd_cnt_zc_rd_ords_04_w	,
      |dd_cnt_zc_rd_ords_01_m	,
      |dd_cnt_zc_rd_ords_02_m	,
      |dd_cnt_zc_rd_ords_03_m	,
      |dd_cnt_zc_rd_ords_04_m	,
      |dd_cnt_zc_rd_ords_05_m	,
      |dd_cnt_zc_rd_ords_06_m	,
      |dd_cnt_kc_rd_ords_01_w	,
      |dd_cnt_kc_rd_ords_02_w	,
      |dd_cnt_kc_rd_ords_03_w	,
      |dd_cnt_kc_rd_ords_04_w	,
      |dd_cnt_kc_rd_ords_01_m	,
      |dd_cnt_kc_rd_ords_02_m	,
      |dd_cnt_kc_rd_ords_03_m	,
      |dd_cnt_kc_rd_ords_04_m	,
      |dd_cnt_kc_rd_ords_05_m	,
      |dd_cnt_kc_rd_ords_06_m	,
      |dd_cnt_kc_rd_ords_tot	,
      |dd_cnt_zc_rd_ords_tot	,
      |dd_amt_zc_coupon_spendpay_01_w	,
      |dd_amt_zc_coupon_spendpay_02_w	,
      |dd_amt_zc_coupon_spendpay_03_w	,
      |dd_amt_zc_coupon_spendpay_04_w	,
      |dd_amt_zc_coupon_spendpay_01_d	,
      |dd_amt_zc_coupon_spendpay_02_d	,
      |dd_amt_zc_coupon_spendpay_03_d	,
      |dd_amt_zc_coupon_spendpay_04_d	,
      |dd_amt_zc_coupon_spendpay_05_d	,
      |dd_amt_zc_coupon_spendpay_06_d	,
      |dd_amt_zc_coupon_spendpay_07_d	,
      |dd_amt_kc_coupon_spendpay_01_d	,
      |dd_amt_kc_coupon_spendpay_02_d	,
      |dd_amt_kc_coupon_spendpay_03_d	,
      |dd_amt_kc_coupon_spendpay_04_d	,
      |dd_amt_kc_coupon_spendpay_05_d	,
      |dd_amt_kc_coupon_spendpay_06_d	,
      |dd_amt_kc_coupon_spendpay_07_d	,
      |dd_amt_kc_coupon_spendpay_01_w	,
      |dd_amt_kc_coupon_spendpay_02_w	,
      |dd_amt_kc_coupon_spendpay_03_w	,
      |dd_amt_kc_coupon_spendpay_04_w	,
      |dd_amt_kc_coupon_spendpay_01_m	,
      |dd_amt_kc_coupon_spendpay_02_m	,
      |dd_amt_kc_coupon_spendpay_03_m	,
      |dd_amt_kc_coupon_spendpay_04_m	,
      |dd_amt_kc_coupon_spendpay_05_m	,
      |dd_amt_kc_coupon_spendpay_06_m	,
      |dd_amt_zc_coupon_spendpay_01_m	,
      |dd_amt_zc_coupon_spendpay_02_m	,
      |dd_amt_zc_coupon_spendpay_03_m	,
      |dd_amt_zc_coupon_spendpay_04_m	,
      |dd_amt_zc_coupon_spendpay_05_m	,
      |dd_amt_zc_coupon_spendpay_06_m	,
      |dd_cnt_kc_coupon_spendpay_tot	,
      |dd_cnt_zc_coupon_spendpay_tot	,
      |dd_amt_zc_payable_cost_01_d	,
      |dd_amt_zc_payable_cost_02_d	,
      |dd_amt_zc_payable_cost_03_d	,
      |dd_amt_zc_payable_cost_04_d	,
      |dd_amt_zc_payable_cost_05_d	,
      |dd_amt_zc_payable_cost_06_d	,
      |dd_amt_zc_payable_cost_07_d	,
      |dd_amt_zc_payable_cost_01_w	,
      |dd_amt_zc_payable_cost_02_w	,
      |dd_amt_zc_payable_cost_03_w	,
      |dd_amt_zc_payable_cost_04_w	,
      |dd_amt_zc_actual_cost_01_w	,
      |dd_amt_zc_actual_cost_02_w	,
      |dd_amt_zc_actual_cost_03_w	,
      |dd_amt_zc_actual_cost_04_w	,
      |dd_amt_zc_payable_cost_01_m	,
      |dd_amt_zc_payable_cost_02_m	,
      |dd_amt_zc_payable_cost_03_m	,
      |dd_amt_zc_payable_cost_04_m	,
      |dd_amt_zc_payable_cost_05_m	,
      |dd_amt_zc_payable_cost_06_m	,
      |dd_amt_kc_payable_cost_01_d	,
      |dd_amt_kc_payable_cost_02_d	,
      |dd_amt_kc_payable_cost_03_d	,
      |dd_amt_kc_payable_cost_04_d	,
      |dd_amt_kc_payable_cost_05_d	,
      |dd_amt_kc_payable_cost_06_d	,
      |dd_amt_kc_payable_cost_07_d	,
      |dd_amt_kc_payable_cost_01_w	,
      |dd_amt_kc_payable_cost_02_w	,
      |dd_amt_kc_payable_cost_03_w	,
      |dd_amt_kc_payable_cost_04_w	,
      |dd_amt_kc_payable_cost_01_m	,
      |dd_amt_kc_payable_cost_02_m	,
      |dd_amt_kc_payable_cost_03_m	,
      |dd_amt_kc_payable_cost_04_m	,
      |dd_amt_kc_payable_cost_05_m	,
      |dd_amt_kc_payable_cost_06_m	,
      |dd_amt_zc_payable_cost_tot	,
      |dd_amt_kc_payable_cost_tot	,
      |dd_amt_zc_actual_cost_01_d	,
      |dd_amt_zc_actual_cost_02_d	,
      |dd_amt_zc_actual_cost_03_d	,
      |dd_amt_zc_actual_cost_04_d	,
      |dd_amt_zc_actual_cost_05_d	,
      |dd_amt_zc_actual_cost_06_d	,
      |dd_amt_zc_actual_cost_07_d	,
      |dd_amt_zc_actual_cost_01_m	,
      |dd_amt_zc_actual_cost_02_m	,
      |dd_amt_zc_actual_cost_03_m	,
      |dd_amt_zc_actual_cost_04_m	,
      |dd_amt_zc_actual_cost_05_m	,
      |dd_amt_zc_actual_cost_06_m	,
      |dd_amt_kc_actual_cost_01_d	,
      |dd_amt_kc_actual_cost_02_d	,
      |dd_amt_kc_actual_cost_03_d	,
      |dd_amt_kc_actual_cost_04_d	,
      |dd_amt_kc_actual_cost_05_d	,
      |dd_amt_kc_actual_cost_06_d	,
      |dd_amt_kc_actual_cost_07_d	,
      |dd_amt_kc_actual_cost_01_w	,
      |dd_amt_kc_actual_cost_02_w	,
      |dd_amt_kc_actual_cost_03_w	,
      |dd_amt_kc_actual_cost_04_w	,
      |dd_amt_kc_actual_cost_01_m	,
      |dd_amt_kc_actual_cost_02_m	,
      |dd_amt_kc_actual_cost_03_m	,
      |dd_amt_kc_actual_cost_04_m	,
      |dd_amt_kc_actual_cost_05_m	,
      |dd_amt_kc_actual_cost_06_m	,
      |dd_amt_zc_actual_cost_tot	,
      |dd_amt_kc_actual_cost_tot	,
      |dd_date_tot_first_succ	,
      |dd_date_tot_last_succ	,
      |dd_date_dc_first_succ	,
      |dd_date_dc_last_succ	,
      |dd_date_zc_first_succ	,
      |dd_date_zc_last_succ	,
      |dd_date_kc_first_succ	,
      |dd_date_kc_last_succ	,
      |dd_date_qy_first_call	,
      |dd_date_qy_last_call	,
      |dd_date_qy_first_succ	,
      |dd_date_qy_last_succ	,
      |kd_date_tot_first_succ	,
      |kd_date_tot_last_succ	,
      |kd_date_dc_first_succ	,
      |kd_date_dc_last_succ	,
      |kd_date_zc_first_succ	,
      |kd_date_zc_last_succ	,
      |kd_date_kc_first_succ	,
      |kd_date_kc_last_succ	,
      |dd_cnt_ord_succ_didi_global	,
      |dd_cnt_ord_didi_global	,
      |dd_cnt_wx_have_bonus_didi_global	,
      |dd_cnt_ord_noresp_tot	,
      |dd_cnt_ord_acpt_tot	,
      |dd_cnt_ord_ariv_tot	,
      |dd_cnt_ord_pkup_tot	,
      |dd_cnt_ord_wait_tot	,
      |dd_cnt_ord_dele_tot	,
      |dd_cnt_wx_pay_ord_tot	,
      |dd_cnt_wx_pay_use_bonus_ord_tot	,
      |dd_cnt_wx_pay_nouse_bonus_ord_tot	,
      |dd_amt_wx_have_bonus_didi_global	,
      |dd_amt_wx_didi_global	,
      |dd_amt_wx_use_bonus_tot	,
      |dd_amt_wx_succ_pay_tot	,
      |dd_amt_zc_coupon_spendpay_tot	,
      |dd_amt_kc_coupon_spendpay_tot	,
      |kd_amt_tot_pay_cost	,
      |year	,
      |month	,
      |day	,
      |pidsn) values
    """.stripMargin


  def main(args: Array[String]): Unit = {
    val fields = fieldSchema.split("\n")
    for(field <- fields) {
      val a = field.split("\t")
      println(a(0) + ":" + a(1))
    }
  }

  val fieldSchema =
    """phone	string
      |dd_reg_time	int
      |kd_reg_time	int
      |type	int
      |district_id	int
      |city_id	int
      |cid	string
      |model	string
      |sex	int
      |appversion	string
      |os	int
      |osversion	string
      |warn_num	int
      |cnt_badorder	int
      |cnt_forbiden	int
      |channel	int
      |status	int
      |flag_uber	int
      |flag_dita	int
      |flag_tiantian	int
      |flag_51	int
      |flag_weiwei	int
      |score_available	int
      |exchange_time	int
      |value	double
      |current_status	int
      |previous_status	int
      |hb_exp	int
      |home_lng	string
      |home_lat	string
      |home	string
      |home_confidence	string
      |company_lng	string
      |company_lat	string
      |company	string
      |company_confidence	string
      |residence_lng	string
      |residence_lat	string
      |residence	string
      |residence_confidence	string
      |app_interest_code	string
      |game_interest_code	string
      |app_id	string
      |game_id	string
      |last_open_app_time	int
      |dd_date_tot_first_call	int
      |dd_date_tot_last_call	int
      |dd_date_dc_first_call	int
      |dd_date_dc_last_call	int
      |dd_date_zc_first_call	int
      |dd_date_zc_last_call	int
      |dd_date_kc_first_call	int
      |dd_date_kc_last_call	int
      |kd_date_tot_first_call	int
      |kd_date_tot_last_call	int
      |kd_date_dc_first_call	int
      |kd_date_dc_last_call	int
      |kd_date_zc_first_call	int
      |kd_date_zc_last_call	int
      |kd_date_kc_first_call	int
      |kd_date_kc_last_call	int
      |kd_has_zc_call	int
      |kd_has_kc_call	int
      |kd_has_dc_call	int
      |kd_has_tot_call	int
      |dd_has_tot_call	int
      |dd_has_zc_call	int
      |dd_has_kc_call	int
      |dd_has_dc_call	int
      |kd_days_kc_call_silence	int
      |kd_days_zc_call_silence	int
      |kd_days_dc_call_silence	int
      |kd_days_tot_call_silenc	int
      |dd_days_tot_call_silence	int
      |dd_days_dc_call_silence	int
      |dd_days_zc_call_silence	int
      |dd_days_kc_call_silence	int
      |dd_days_qy_call_silence	int
      |dd_has_qy_call	int
      |dd_has_tot_succ	int
      |dd_has_dc_succ	int
      |dd_has_zc_succ	int
      |dd_has_kc_succ	int
      |kd_has_tot_succ	int
      |kd_has_dc_succ	int
      |kd_has_zc_succ	int
      |kd_has_kc_succ	int
      |dd_has_qy_succ	int
      |dd_cnt_ord_call_01_d	int
      |dd_cnt_ord_call_02_d	int
      |dd_cnt_ord_call_03_d	int
      |dd_cnt_ord_call_04_d	int
      |dd_cnt_ord_call_05_d	int
      |dd_cnt_ord_call_06_d	int
      |dd_cnt_ord_call_07_d	int
      |dd_cnt_ord_call_01_w	int
      |dd_cnt_ord_call_02_w	int
      |dd_cnt_ord_call_03_w	int
      |dd_cnt_ord_call_04_w	int
      |dd_cnt_ord_call_01_m	int
      |dd_cnt_ord_call_02_m	int
      |dd_cnt_ord_call_03_m	int
      |dd_cnt_ord_call_04_m	int
      |dd_cnt_ord_call_05_m	int
      |dd_cnt_ord_call_06_m	int
      |dd_cnt_zc_call_01_d	int
      |dd_cnt_zc_call_02_d	int
      |dd_cnt_zc_call_03_d	int
      |dd_cnt_zc_call_04_d	int
      |dd_cnt_zc_call_05_d	int
      |dd_cnt_zc_call_06_d	int
      |dd_cnt_zc_call_07_d	int
      |dd_cnt_kc_call_01_d	int
      |dd_cnt_kc_call_02_d	int
      |dd_cnt_kc_call_03_d	int
      |dd_cnt_kc_call_04_d	int
      |dd_cnt_kc_call_05_d	int
      |dd_cnt_kc_call_06_d	int
      |dd_cnt_kc_call_07_d	int
      |kd_cnt_zc_call_ord_01_d	int
      |kd_cnt_zc_call_ord_02_d	int
      |kd_cnt_zc_call_ord_03_d	int
      |kd_cnt_zc_call_ord_04_d	int
      |kd_cnt_zc_call_ord_05_d	int
      |kd_cnt_zc_call_ord_06_d	int
      |kd_cnt_zc_call_ord_07_d	int
      |kd_cnt_kc_call_ord_01_d	int
      |kd_cnt_kc_call_ord_02_d	int
      |kd_cnt_kc_call_ord_03_d	int
      |kd_cnt_kc_call_ord_04_d	int
      |kd_cnt_kc_call_ord_05_d	int
      |kd_cnt_kc_call_ord_06_d	int
      |kd_cnt_kc_call_ord_07_d	int
      |kd_cnt_taxi_call_ord_01_d	int
      |kd_cnt_taxi_call_ord_02_d	int
      |kd_cnt_taxi_call_ord_03_d	int
      |kd_cnt_taxi_call_ord_04_d	int
      |kd_cnt_taxi_call_ord_05_d	int
      |kd_cnt_taxi_call_ord_06_d	int
      |kd_cnt_taxi_call_ord_07_d	int
      |kd_cnt_call_ord_01_d	int
      |kd_cnt_call_ord_02_d	int
      |kd_cnt_call_ord_03_d	int
      |kd_cnt_call_ord_04_d	int
      |kd_cnt_call_ord_05_d	int
      |kd_cnt_call_ord_06_d	int
      |kd_cnt_call_ord_07_d	int
      |kd_cnt_succ_ord_01_d	int
      |kd_cnt_succ_ord_02_d	int
      |kd_cnt_succ_ord_03_d	int
      |kd_cnt_succ_ord_04_d	int
      |kd_cnt_succ_ord_05_d	int
      |kd_cnt_succ_ord_06_d	int
      |kd_cnt_succ_ord_07_d	int
      |dd_cnt_zc_call_01_w	int
      |dd_cnt_zc_call_02_w	int
      |dd_cnt_zc_call_03_w	int
      |dd_cnt_zc_call_04_w	int
      |dd_cnt_kc_call_01_w	int
      |dd_cnt_kc_call_02_w	int
      |dd_cnt_kc_call_03_w	int
      |dd_cnt_kc_call_04_w	int
      |kd_cnt_zc_call_ord_01_w	int
      |kd_cnt_zc_call_ord_02_w	int
      |kd_cnt_zc_call_ord_03_w	int
      |kd_cnt_zc_call_ord_04_w	int
      |kd_cnt_kc_call_ord_01_w	int
      |kd_cnt_kc_call_ord_02_w	int
      |kd_cnt_kc_call_ord_03_w	int
      |kd_cnt_kc_call_ord_04_w	int
      |kd_cnt_taxi_call_ord_01_w	int
      |kd_cnt_taxi_call_ord_02_w	int
      |kd_cnt_taxi_call_ord_03_w	int
      |kd_cnt_taxi_call_ord_04_w	int
      |kd_cnt_call_ord_01_w	int
      |kd_cnt_call_ord_02_w	int
      |kd_cnt_call_ord_03_w	int
      |kd_cnt_call_ord_04_w	int
      |dd_cnt_zc_call_01_m	int
      |dd_cnt_zc_call_02_m	int
      |dd_cnt_zc_call_03_m	int
      |dd_cnt_zc_call_04_m	int
      |dd_cnt_zc_call_05_m	int
      |dd_cnt_zc_call_06_m	int
      |dd_cnt_kc_call_01_m	int
      |dd_cnt_kc_call_02_m	int
      |dd_cnt_kc_call_03_m	int
      |dd_cnt_kc_call_04_m	int
      |dd_cnt_kc_call_05_m	int
      |dd_cnt_kc_call_06_m	int
      |kd_cnt_zc_call_ord_01_m	int
      |kd_cnt_zc_call_ord_02_m	int
      |kd_cnt_zc_call_ord_03_m	int
      |kd_cnt_zc_call_ord_04_m	int
      |kd_cnt_zc_call_ord_05_m	int
      |kd_cnt_zc_call_ord_06_m	int
      |kd_cnt_kc_call_ord_01_m	int
      |kd_cnt_kc_call_ord_02_m	int
      |kd_cnt_kc_call_ord_03_m	int
      |kd_cnt_kc_call_ord_04_m	int
      |kd_cnt_kc_call_ord_05_m	int
      |kd_cnt_kc_call_ord_06_m	int
      |kd_cnt_taxi_call_ord_01_m	int
      |kd_cnt_taxi_call_ord_02_m	int
      |kd_cnt_taxi_call_ord_03_m	int
      |kd_cnt_taxi_call_ord_04_m	int
      |kd_cnt_taxi_call_ord_05_m	int
      |kd_cnt_taxi_call_ord_06_m	int
      |kd_cnt_call_ord_01_m	int
      |kd_cnt_call_ord_02_m	int
      |kd_cnt_call_ord_03_m	int
      |kd_cnt_call_ord_04_m	int
      |kd_cnt_call_ord_05_m	int
      |kd_cnt_call_ord_06_m	int
      |dd_cnt_zc_preferred_call_01_m	int
      |dd_cnt_zc_preferred_call_02_m	int
      |dd_cnt_zc_preferred_call_03_m	int
      |dd_cnt_zc_preferred_call_04_m	int
      |dd_cnt_zc_preferred_call_05_m	int
      |dd_cnt_zc_preferred_call_06_m	int
      |dd_cnt_zc_comfortable_call_01_m	int
      |dd_cnt_zc_comfortable_call_02_m	int
      |dd_cnt_zc_comfortable_call_03_m	int
      |dd_cnt_zc_comfortable_call_04_m	int
      |dd_cnt_zc_comfortable_call_05_m	int
      |dd_cnt_zc_comfortable_call_06_m	int
      |dd_cnt_zc_business_call_01_m	int
      |dd_cnt_zc_business_call_02_m	int
      |dd_cnt_zc_business_call_03_m	int
      |dd_cnt_zc_business_call_04_m	int
      |dd_cnt_zc_business_call_05_m	int
      |dd_cnt_zc_business_call_06_m	int
      |dd_cnt_zc_premium_call_01_m	int
      |dd_cnt_zc_premium_call_02_m	int
      |dd_cnt_zc_premium_call_03_m	int
      |dd_cnt_zc_premium_call_04_m	int
      |dd_cnt_zc_premium_call_05_m	int
      |dd_cnt_zc_premium_call_06_m	int
      |dd_cnt_zc_call_tot	int
      |dd_cnt_zc_preferred_call_tot	int
      |dd_cnt_zc_comfortable_call_tot	int
      |dd_cnt_zc_business_call_tot	int
      |dd_cnt_zc_premium_call_tot	int
      |dd_cnt_kc_call_tot	int
      |kd_cnt_tot_call_ords	int
      |dd_cnt_ord_call_tot	int
      |dd_cnt_ord_succ_01_d	int
      |dd_cnt_ord_succ_02_d	int
      |dd_cnt_ord_succ_03_d	int
      |dd_cnt_ord_succ_04_d	int
      |dd_cnt_ord_succ_05_d	int
      |dd_cnt_ord_succ_06_d	int
      |dd_cnt_ord_succ_07_d	int
      |dd_cnt_zc_succ_call_01_d	int
      |dd_cnt_zc_succ_call_02_d	int
      |dd_cnt_zc_succ_call_03_d	int
      |dd_cnt_zc_succ_call_04_d	int
      |dd_cnt_zc_succ_call_05_d	int
      |dd_cnt_zc_succ_call_06_d	int
      |dd_cnt_zc_succ_call_07_d	int
      |dd_cnt_kc_succ_call_01_d	int
      |dd_cnt_kc_succ_call_02_d	int
      |dd_cnt_kc_succ_call_03_d	int
      |dd_cnt_kc_succ_call_04_d	int
      |dd_cnt_kc_succ_call_05_d	int
      |dd_cnt_kc_succ_call_06_d	int
      |dd_cnt_kc_succ_call_07_d	int
      |kd_cnt_zc_succ_ord_01_d	int
      |kd_cnt_zc_succ_ord_02_d	int
      |kd_cnt_zc_succ_ord_03_d	int
      |kd_cnt_zc_succ_ord_04_d	int
      |kd_cnt_zc_succ_ord_05_d	int
      |kd_cnt_zc_succ_ord_06_d	int
      |kd_cnt_zc_succ_ord_07_d	int
      |kd_cnt_kc_succ_ord_01_d	int
      |kd_cnt_kc_succ_ord_02_d	int
      |kd_cnt_kc_succ_ord_03_d	int
      |kd_cnt_kc_succ_ord_04_d	int
      |kd_cnt_kc_succ_ord_05_d	int
      |kd_cnt_kc_succ_ord_06_d	int
      |kd_cnt_kc_succ_ord_07_d	int
      |kd_cnt_taxi_succ_ord_01_d	int
      |kd_cnt_taxi_succ_ord_02_d	int
      |kd_cnt_taxi_succ_ord_03_d	int
      |kd_cnt_taxi_succ_ord_04_d	int
      |kd_cnt_taxi_succ_ord_05_d	int
      |kd_cnt_taxi__succ_ord_06_d	int
      |kd_cnt_taxi__succ_ord_07_d	int
      |dd_cnt_ord_succ_01_w	int
      |dd_cnt_ord_succ_02_w	int
      |dd_cnt_ord_succ_03_w	int
      |dd_cnt_ord_succ_04_w	int
      |dd_cnt_zc_succ_call_01_w	int
      |dd_cnt_zc_succ_call_02_w	int
      |dd_cnt_zc_succ_call_03_w	int
      |dd_cnt_zc_succ_call_04_w	int
      |dd_cnt_kc_succ_call_01_w	int
      |dd_cnt_kc_succ_call_02_w	int
      |dd_cnt_kc_succ_call_03_w	int
      |dd_cnt_kc_succ_call_04_w	int
      |kd_cnt_zc_succ_ord_01_w	int
      |kd_cnt_zc_succ_ord_02_w	int
      |kd_cnt_zc_succ_ord_03_w	int
      |kd_cnt_zc_succ_ord_04_w	int
      |kd_cnt_kc_succ_ord_01_w	int
      |kd_cnt_kc_succ_ord_02_w	int
      |kd_cnt_kc_succ_ord_03_w	int
      |kd_cnt_kc_succ_ord_04_w	int
      |kd_cnt_taxi_succ_ord_01_w	int
      |kd_cnt_taxi_succ_ord_02_w	int
      |kd_cnt_taxi_succ_ord_03_w	int
      |kd_cnt_taxi_succ_ord_04_w	int
      |kd_cnt_succ_ord_01_w	int
      |kd_cnt_succ_ord_02_w	int
      |kd_cnt_succ_ord_03_w	int
      |kd_cnt_succ_ord_04_w	int
      |dd_cnt_ord_succ_01_m	int
      |dd_cnt_ord_succ_02_m	int
      |dd_cnt_ord_succ_03_m	int
      |dd_cnt_ord_succ_04_m	int
      |dd_cnt_ord_succ_05_m	int
      |dd_cnt_ord_succ_06_m	int
      |dd_cnt_ord_succ_tot	int
      |dd_cnt_zc_succ_call_01_m	int
      |dd_cnt_zc_succ_call_02_m	int
      |dd_cnt_zc_succ_call_03_m	int
      |dd_cnt_zc_succ_call_04_m	int
      |dd_cnt_zc_succ_call_05_m	int
      |dd_cnt_zc_succ_call_06_m	int
      |dd_cnt_zc_preferred_succ_ords_01_m	int
      |dd_cnt_zc_preferred_succ_ords_02_m	int
      |dd_cnt_zc_preferred_succ_ords_03_m	int
      |dd_cnt_zc_preferred_succ_ords_04_m	int
      |dd_cnt_zc_preferred_succ_ords_05_m	int
      |dd_cnt_zc_preferred_succ_ords_06_m	int
      |dd_cnt_zc_comfortable_succ_ords_01_m	int
      |dd_cnt_zc_comfortable_succ_ords_02_m	int
      |dd_cnt_zc_comfortable_succ_ords_03_m	int
      |dd_cnt_zc_comfortable_succ_ords_04_m	int
      |dd_cnt_zc_comfortable_succ_ords_05_m	int
      |dd_cnt_zc_comfortable_succ_ords_06_m	int
      |dd_cnt_zc_business_succ_ords_01_m	int
      |dd_cnt_zc_business_succ_ords_02_m	int
      |dd_cnt_zc_business_succ_ords_03_m	int
      |dd_cnt_zc_business_succ_ords_04_m	int
      |dd_cnt_zc_business_succ_ords_05_m	int
      |dd_cnt_zc_business_succ_ords_06_m	int
      |dd_cnt_zc_premium_succ_ords_01_m	int
      |dd_cnt_zc_premium_succ_ords_02_m	int
      |dd_cnt_zc_premium_succ_ords_03_m	int
      |dd_cnt_zc_premium_succ_ords_04_m	int
      |dd_cnt_zc_premium_succ_ords_05_m	int
      |dd_cnt_zc_premium_succ_ords_06_m	int
      |dd_cnt_kc_succ_call_01_m	int
      |dd_cnt_kc_succ_call_02_m	int
      |dd_cnt_kc_succ_call_03_m	int
      |dd_cnt_kc_succ_call_04_m	int
      |dd_cnt_kc_succ_call_05_m	int
      |dd_cnt_kc_succ_call_06_m	int
      |kd_cnt_zc_succ_ord_01_m	int
      |kd_cnt_zc_succ_ord_02_m	int
      |kd_cnt_zc_succ_ord_03_m	int
      |kd_cnt_zc_succ_ord_04_m	int
      |kd_cnt_zc_succ_ord_05_m	int
      |kd_cnt_zc_succ_ord_06_m	int
      |kd_cnt_kc_succ_ord_01_m	int
      |kd_cnt_kc_succ_ord_02_m	int
      |kd_cnt_kc_succ_ord_03_m	int
      |kd_cnt_kc_succ_ord_04_m	int
      |kd_cnt_kc_succ_ord_05_m	int
      |kd_cnt_kc_succ_ord_06_m	int
      |kd_cnt_taxi_succ_ord_01_m	int
      |kd_cnt_taxi_succ_ord_02_m	int
      |kd_cnt_taxi_succ_ord_03_m	int
      |kd_cnt_taxi_succ_ord_04_m	int
      |kd_cnt_taxi_succ_ord_05_m	int
      |kd_cnt_taxi_succ_ord_06_m	int
      |kd_cnt_succ_ord_01_m	int
      |kd_cnt_succ_ord_02_m	int
      |kd_cnt_succ_ord_03_m	int
      |kd_cnt_succ_ord_04_m	int
      |kd_cnt_succ_ord_05_m	int
      |kd_cnt_succ_ord_06_m	int
      |dd_cnt_zc_succ_call_tot	int
      |dd_cnt_zc_preferred_succ_ords_tot	int
      |dd_cnt_zc_comfortable_succ_ords_tot	int
      |dd_cnt_zc_business_succ_ords_tot	int
      |dd_cnt_zc_premium_succ_ords_tot	int
      |dd_cnt_kc_succ_call_tot	int
      |dd_cnt_ord_pass_cacled_tot	int
      |dd_cnt_ord_pass_cacl_tot	int
      |dd_cnt_zc_aft_strive_pcancel_call_tot	int
      |dd_cnt_zc_bef_strive_pcancel_call_tot	int
      |dd_cnt_kc_aft_strive_pcancel_call_tot	int
      |dd_cnt_kc_bef_strive_pcancel_call_tot	int
      |kd_cnt_tot_pass_cancle_ords	int
      |kd_cnt_zc_pass_cancle_ord_01_d	int
      |kd_cnt_zc_pass_cancle_ord_02_d	int
      |kd_cnt_zc_pass_cancle_ord_03_d	int
      |kd_cnt_zc_pass_cancle_ord_04_d	int
      |kd_cnt_zc_pass_cancle_ord_05_d	int
      |kd_cnt_zc_pass_cancle_ord_06_d	int
      |kd_cnt_zc_pass_cancle_ord_07_d	int
      |kd_cnt_kc_pass_cancle_ord_01_d	int
      |kd_cnt_kc_pass_cancle_ord_02_d	int
      |kd_cnt_kc_pass_cancle_ord_03_d	int
      |kd_cnt_kc_pass_cancle_ord_04_d	int
      |kd_cnt_kc_pass_cancle_ord_05_d	int
      |kd_cnt_kc_pass_cancle_ord_06_d	int
      |kd_cnt_kc_pass_cancle_ord_07_d	int
      |kd_cnt_taxi_pass_cancle_ord_01_d	int
      |kd_cnt_taxi_pass_cancle_ord_02_d	int
      |kd_cnt_taxi_pass_cancle_ord_03_d	int
      |kd_cnt_taxi_pass_cancle_ord_04_d	int
      |kd_cnt_taxi_pass_cancle_ord_05_d	int
      |kd_cnt_taxi_pass_cancle_ord_06_d	int
      |kd_cnt_taxi_pass_cancle_ord_07_d	int
      |kd_cnt_pass_cancle_ord_01_d	int
      |kd_cnt_pass_cancle_ord_02_d	int
      |kd_cnt_pass_cancle_ord_03_d	int
      |kd_cnt_pass_cancle_ord_04_d	int
      |kd_cnt_pass_cancle_ord_05_d	int
      |kd_cnt_pass_cancle_ord_06_d	int
      |kd_cnt_pass_cancle_ord_07_d	int
      |kd_cnt_taxi_pass_cancle_ord_01_w	int
      |kd_cnt_taxi_pass_cancle_ord_02_w	int
      |kd_cnt_taxi_pass_cancle_ord_03_w	int
      |kd_cnt_taxi_pass_cancle_ord_04_w	int
      |kd_cnt_pass_cancle_ord_01_w	int
      |kd_cnt_pass_cancle_ord_02_w	int
      |kd_cnt_pass_cancle_ord_03_w	int
      |kd_cnt_pass_cancle_ord_04_w	int
      |kd_cnt_zc_pass_cancle_ord_01_m	int
      |kd_cnt_zc_pass_cancle_ord_02_m	int
      |kd_cnt_zc_pass_cancle_ord_03_m	int
      |kd_cnt_zc_pass_cancle_ord_04_m	int
      |kd_cnt_zc_pass_cancle_ord_05_m	int
      |kd_cnt_zc_pass_cancle_ord_06_m	int
      |kd_cnt_kc_pass_cancle_ord_01_m	int
      |kd_cnt_kc_pass_cancle_ord_02_m	int
      |kd_cnt_kc_pass_cancle_ord_03_m	int
      |kd_cnt_kc_pass_cancle_ord_04_m	int
      |kd_cnt_kc_pass_cancle_ord_05_m	int
      |kd_cnt_kc_pass_cancle_ord_06_m	int
      |kd_cnt_taxi_pass_cancle_ord_01_m	int
      |kd_cnt_taxi_pass_cancle_ord_02_m	int
      |kd_cnt_taxi_pass_cancle_ord_03_m	int
      |kd_cnt_taxi_pass_cancle_ord_04_m	int
      |kd_cnt_taxi_pass_cancle_ord_05_m	int
      |kd_cnt_taxi_pass_cancle_ord_06_m	int
      |kd_cnt_pass_cancle_ord_01_m	int
      |kd_cnt_pass_cancle_ord_02_m	int
      |kd_cnt_pass_cancle_ord_03_m	int
      |kd_cnt_pass_cancle_ord_04_m	int
      |kd_cnt_pass_cancle_ord_05_m	int
      |kd_cnt_pass_cancle_ord_06_m	int
      |dd_cnt_ord_cacl_01_m	int
      |dd_cnt_ord_cacl_02_m	int
      |dd_cnt_ord_cacl_03_m	int
      |dd_cnt_ord_cacl_04_m	int
      |dd_cnt_ord_cacl_05_m	int
      |dd_cnt_ord_cacl_06_m	int
      |dd_cnt_ord_nodeal_01_m	int
      |dd_cnt_ord_nodeal_02_m	int
      |dd_cnt_ord_nodeal_03_m	int
      |dd_cnt_ord_nodeal_04_m	int
      |dd_cnt_ord_nodeal_05_m	int
      |dd_cnt_ord_nodeal_06_m	int
      |dd_cnt_ord_nodeal_tot	int
      |dd_cnt_ord_bonus_lift_5_tot	int
      |dd_cnt_ord_bonus_lift_10_tot	int
      |dd_cnt_ord_bonus_lift_15_tot	int
      |dd_cnt_ord_bonus_lift_20_tot	int
      |dd_cnt_ord_succ_bonus_lift_tot	int
      |dd_cnt_ord_bonus_lift_tot	int
      |dd_cnt_ord_bonus_lift_01_w	int
      |dd_cnt_ord_bonus_lift_02_w	int
      |dd_cnt_ord_bonus_lift_03_w	int
      |dd_cnt_ord_bonus_lift_04_w	int
      |dd_cnt_ord_bonus_lift_01_m	int
      |dd_cnt_ord_bonus_lift_02_m	int
      |dd_cnt_ord_bonus_lift_03_m	int
      |dd_cnt_ord_bonus_lift_04_m	int
      |dd_cnt_ord_bonus_lift_05_m	int
      |dd_cnt_ord_bonus_lift_06_m	int
      |dd_amt_ord_bonus_lift_01_w	double
      |dd_amt_ord_bonus_lift_02_w	double
      |dd_amt_ord_bonus_lift_03_w	double
      |dd_amt_ord_bonus_lift_04_w	double
      |dd_amt_ord_bonus_lift_01_m	double
      |dd_amt_ord_bonus_lift_02_m	double
      |dd_amt_ord_bonus_lift_03_m	double
      |dd_amt_ord_bonus_lift_04_m	double
      |dd_amt_ord_bonus_lift_05_m	double
      |dd_amt_ord_bonus_lift_06_m	double
      |dd_amt_ord_succ_bonus_lift_tot	double
      |dd_amt_ord_bonus_lift_tot	double
      |dd_cnt_rob_succ_days_01_w	int
      |dd_cnt_rob_succ_days_02_w	int
      |dd_cnt_rob_succ_days_03_w	int
      |dd_cnt_rob_succ_days_04_w	int
      |kd_cnt_zc_succ_ord_days_01_w	int
      |kd_cnt_zc_succ_ord_days_02_w	int
      |kd_cnt_zc_succ_ord_days_03_w	int
      |kd_cnt_zc_succ_ord_days_04_w	int
      |kd_cnt_kc_succ_ord_days_01_w	int
      |kd_cnt_kc_succ_ord_days_02_w	int
      |kd_cnt_kc_succ_ord_days_03_w	int
      |kd_cnt_kc_succ_ord_days_04_w	int
      |kd_cnt_taxi_succ_ord_days_01_w	int
      |kd_cnt_taxi_succ_ord_days_02_w	int
      |kd_cnt_taxi_succ_ord_days_03_w	int
      |kd_cnt_taxi_succ_ord_days_04_w	int
      |kd_cnt_succ_ord_days_01_w	int
      |kd_cnt_succ_ord_days_02_w	int
      |kd_cnt_succ_ord_days_03_w	int
      |kd_cnt_succ_ord_days_04_w	int
      |kd_cnt_zc_succ_ord_days_01_m	int
      |kd_cnt_zc_succ_ord_days_02_m	int
      |kd_cnt_zc_succ_ord_days_03_m	int
      |kd_cnt_zc_succ_ord_days_04_m	int
      |kd_cnt_zc_succ_ord_days_05_m	int
      |kd_cnt_zc_succ_ord_days_06_m	int
      |kd_cnt_kc_succ_ord_days_01_m	int
      |kd_cnt_kc_succ_ord_days_02_m	int
      |kd_cnt_kc_succ_ord_days_03_m	int
      |kd_cnt_kc_succ_ord_days_04_m	int
      |kd_cnt_kc_succ_ord_days_05_m	int
      |kd_cnt_kc_succ_ord_days_06_m	int
      |kd_cnt_taxi_succ_ord_days_01_m	int
      |kd_cnt_taxi_succ_ord_days_02_m	int
      |kd_cnt_taxi_succ_ord_days_03_m	int
      |kd_cnt_taxi_succ_ord_days_04_m	int
      |kd_cnt_taxi_succ_ord_days_05_m	int
      |kd_cnt_taxi_succ_ord_days_06_m	int
      |kd_cnt_succ_ord_days_01_m	int
      |kd_cnt_succ_ord_days_02_m	int
      |kd_cnt_succ_ord_days_03_m	int
      |kd_cnt_succ_ord_days_04_m	int
      |kd_cnt_succ_ord_days_05_m	int
      |kd_cnt_succ_ord_days_06_m	int
      |kd_cnt_tot_succ_ord_days	int
      |kd_cnt_tot_call_days	int
      |dd_cnt_call_days_14_d	int
      |dd_cnt_call_days_30_d	int
      |kd_cnt_zc_call_days_01_w	int
      |kd_cnt_zc_call_days_02_w	int
      |kd_cnt_zc_call_days_03_w	int
      |kd_cnt_zc_call_days_04_w	int
      |kd_cnt_kc_call_days_01_w	int
      |kd_cnt_kc_call_days_02_w	int
      |kd_cnt_kc_call_days_03_w	int
      |kd_cnt_kc_call_days_04_w	int
      |kd_cnt_taxi_call_days_01_w	int
      |kd_cnt_taxi_call_days_02_w	int
      |kd_cnt_taxi_call_days_03_w	int
      |kd_cnt_taxi_call_days_04_w	int
      |kd_cnt_call_days_01_w	int
      |kd_cnt_call_days_02_w	int
      |kd_cnt_call_days_03_w	int
      |kd_cnt_call_days_04_w	int
      |kd_cnt_zc_call_days_01_m	int
      |kd_cnt_zc_call_days_02_m	int
      |kd_cnt_zc_call_days_03_m	int
      |kd_cnt_zc_call_days_04_m	int
      |kd_cnt_zc_call_days_05_m	int
      |kd_cnt_zc_call_days_06_m	int
      |kd_cnt_kc_call_days_01_m	int
      |kd_cnt_kc_call_days_02_m	int
      |kd_cnt_kc_call_days_03_m	int
      |kd_cnt_kc_call_days_04_m	int
      |kd_cnt_kc_call_days_05_m	int
      |kd_cnt_kc_call_days_06_m	int
      |kd_cnt_taxi_call_days_01_m	int
      |kd_cnt_taxi_call_days_02_m	int
      |kd_cnt_taxi_call_days_03_m	int
      |kd_cnt_taxi_call_days_04_m	int
      |kd_cnt_taxi_call_days_05_m	int
      |kd_cnt_taxi_call_days_06_m	int
      |kd_cnt_call_days_01_m	int
      |kd_cnt_call_days_02_m	int
      |kd_cnt_call_days_03_m	int
      |kd_cnt_call_days_04_m	int
      |kd_cnt_call_days_05_m	int
      |kd_cnt_call_days_06_m	int
      |dd_secs_zc_strive_01_w	int
      |dd_secs_zc_strive_02_w	int
      |dd_secs_zc_strive_03_w	int
      |dd_secs_zc_strive_04_w	int
      |dd_secs_zc_strive_01_m	int
      |dd_secs_zc_strive_02_m	int
      |dd_secs_zc_strive_03_m	int
      |dd_secs_zc_strive_04_m	int
      |dd_secs_zc_strive_05_m	int
      |dd_secs_zc_strive_06_m	int
      |dd_secs_kc_strive_01_d	int
      |dd_secs_kc_strive_02_d	int
      |dd_secs_kc_strive_03_d	int
      |dd_secs_kc_strive_04_d	int
      |dd_secs_kc_strive_05_d	int
      |dd_secs_kc_strive_06_d	int
      |dd_secs_kc_strive_07_d	int
      |dd_secs_kc_strive_01_w	int
      |dd_secs_kc_strive_02_w	int
      |dd_secs_kc_strive_03_w	int
      |dd_secs_kc_strive_04_w	int
      |dd_secs_kc_strive_01_m	int
      |dd_secs_kc_strive_02_m	int
      |dd_secs_kc_strive_03_m	int
      |dd_secs_kc_strive_04_m	int
      |dd_secs_kc_strive_05_m	int
      |dd_secs_kc_strive_06_m	int
      |dd_secs_kc_strive_tot	int
      |dd_secs_zc_strive_tot	int
      |dd_secs_zc_pwait_01_w	int
      |dd_secs_zc_pwait_02_w	int
      |dd_secs_zc_pwait_03_w	int
      |dd_secs_zc_pwait_04_w	int
      |dd_secs_zc_wwait_01_w	int
      |dd_secs_zc_wwait_02_w	int
      |dd_secs_zc_wwait_03_w	int
      |dd_secs_zc_wwait_04_w	int
      |dd_secs_zc_pwait_01_m	int
      |dd_secs_zc_pwait_02_m	int
      |dd_secs_zc_pwait_03_m	int
      |dd_secs_zc_pwait_04_m	int
      |dd_secs_zc_pwait_05_m	int
      |dd_secs_zc_pwait_06_m	int
      |dd_secs_zc_mwait_01_m	int
      |dd_secs_zc_mwait_02_m	int
      |dd_secs_zc_mwait_03_m	int
      |dd_secs_zc_mwait_04_m	int
      |dd_secs_zc_mwait_05_m	int
      |dd_secs_zc_mwait_06_m	int
      |dd_secs_zc_pwait_tot	int
      |dd_secs_zc_totwait_tot	int
      |dd_secs_kc_pwait_01_m	int
      |dd_secs_kc_pwait_02_m	int
      |dd_secs_kc_pwait_03_m	int
      |dd_secs_kc_pwait_04_m	int
      |dd_secs_kc_pwait_05_m	int
      |dd_secs_kc_pwait_06_m	int
      |dd_secs_kc_mwait_01_m	int
      |dd_secs_kc_mwait_02_m	int
      |dd_secs_kc_mwait_03_m	int
      |dd_secs_kc_mwait_04_m	int
      |dd_secs_kc_mwait_05_m	int
      |dd_secs_kc_mwait_06_m	int
      |dd_secs_kc_pwait_tot	int
      |dd_secs_kc_totwait_tot	int
      |dd_cnt_wx_pay_succ_ord_01_d	int
      |dd_cnt_wx_pay_succ_ord_02_d	int
      |dd_cnt_wx_pay_succ_ord_03_d	int
      |dd_cnt_wx_pay_succ_ord_04_d	int
      |dd_cnt_wx_pay_succ_ord_05_d	int
      |dd_cnt_wx_pay_succ_ord_06_d	int
      |dd_cnt_wx_pay_succ_ord_07_d	int
      |kd_cnt_zc_pay_succ_ord_01_d	int
      |kd_cnt_zc_pay_succ_ord_02_d	int
      |kd_cnt_zc_pay_succ_ord_03_d	int
      |kd_cnt_zc_pay_succ_ord_04_d	int
      |kd_cnt_zc_pay_succ_ord_05_d	int
      |kd_cnt_zc_pay_succ_ord_06_d	int
      |kd_cnt_zc_pay_succ_ord_07_d	int
      |kd_cnt_kc_pay_succ_ord_01_d	int
      |kd_cnt_kc_pay_succ_ord_02_d	int
      |kd_cnt_kc_pay_succ_ord_03_d	int
      |kd_cnt_kc_pay_succ_ord_04_d	int
      |kd_cnt_kc_pay_succ_ord_05_d	int
      |kd_cnt_kc_pay_succ_ord_06_d	int
      |kd_cnt_kc_pay_succ_ord_07_d	int
      |kd_cnt_taxi_pay_succ_ord_01_d	int
      |kd_cnt_taxi_pay_succ_ord_02_d	int
      |kd_cnt_taxi_pay_succ_ord_03_d	int
      |kd_cnt_taxi_pay_succ_ord_04_d	int
      |kd_cnt_taxi_pay_succ_ord_05_d	int
      |kd_cnt_taxi_pay_succ_ord_06_d	int
      |kd_cnt_taxi_pay_succ_ord_07_d	int
      |kd_cnt_pay_succ_ord_01_d	int
      |kd_cnt_pay_succ_ord_02_d	int
      |kd_cnt_pay_succ_ord_03_d	int
      |kd_cnt_pay_succ_ord_04_d	int
      |kd_cnt_pay_succ_ord_05_d	int
      |kd_cnt_pay_succ_ord_06_d	int
      |kd_cnt_pay_succ_ord_07_d	int
      |dd_cnt_wx_pay_succ_ord_01_w	int
      |dd_cnt_wx_pay_succ_ord_02_w	int
      |dd_cnt_wx_pay_succ_ord_03_w	int
      |dd_cnt_wx_pay_succ_ord_04_w	int
      |kd_cnt_zc_pay_succ_ord_01_w	int
      |kd_cnt_zc_pay_succ_ord_02_w	int
      |kd_cnt_zc_pay_succ_ord_03_w	int
      |kd_cnt_zc_pay_succ_ord_04_w	int
      |kd_cnt_kc_pay_succ_ord_01_w	int
      |kd_cnt_kc_pay_succ_ord_02_w	int
      |kd_cnt_kc_pay_succ_ord_03_w	int
      |kd_cnt_kc_pay_succ_ord_04_w	int
      |kd_cnt_taxi_pay_succ_ord_01_w	int
      |kd_cnt_taxi_pay_succ_ord_02_w	int
      |kd_cnt_taxi_pay_succ_ord_03_w	int
      |kd_cnt_taxi_pay_succ_ord_04_w	int
      |kd_cnt_pay_succ_ord_01_w	int
      |kd_cnt_pay_succ_ord_02_w	int
      |kd_cnt_pay_succ_ord_03_w	int
      |kd_cnt_pay_succ_ord_04_w	int
      |dd_cnt_wx_pay_succ_ord_01_m	int
      |dd_cnt_wx_pay_succ_ord_02_m	int
      |dd_cnt_wx_pay_succ_ord_03_m	int
      |dd_cnt_wx_pay_succ_ord_04_m	int
      |dd_cnt_wx_pay_succ_ord_05_m	int
      |dd_cnt_wx_pay_succ_ord_06_m	int
      |kd_cnt_zc_pay_succ_ord_01_m	int
      |kd_cnt_zc_pay_succ_ord_02_m	int
      |kd_cnt_zc_pay_succ_ord_03_m	int
      |kd_cnt_zc_pay_succ_ord_04_m	int
      |kd_cnt_zc_pay_succ_ord_05_m	int
      |kd_cnt_zc_pay_succ_ord_06_m	int
      |kd_cnt_kc_pay_succ_ord_01_m	int
      |kd_cnt_kc_pay_succ_ord_02_m	int
      |kd_cnt_kc_pay_succ_ord_03_m	int
      |kd_cnt_kc_pay_succ_ord_04_m	int
      |kd_cnt_kc_pay_succ_ord_05_m	int
      |kd_cnt_kc_pay_succ_ord_06_m	int
      |kd_cnt_taxi_pay_succ_ord_01_m	int
      |kd_cnt_taxi_pay_succ_ord_02_m	int
      |kd_cnt_taxi_pay_succ_ord_03_m	int
      |kd_cnt_taxi_pay_succ_ord_04_m	int
      |kd_cnt_taxi_pay_succ_ord_05_m	int
      |kd_cnt_taxi_pay_succ_ord_06_m	int
      |kd_cnt_pay_succ_ord_01_m	int
      |kd_cnt_pay_succ_ord_02_m	int
      |kd_cnt_pay_succ_ord_03_m	int
      |kd_cnt_pay_succ_ord_04_m	int
      |kd_cnt_pay_succ_ord_05_m	int
      |kd_cnt_pay_succ_ord_06_m	int
      |dd_cnt_wx_pay_succ_ord_tot	int
      |kd_cnt_tot_pay_succ_ords	int
      |dd_cnt_wx_succ_didi_global	int
      |dd_cnt_ord_pay_fin_tot	int
      |dd_cnt_wx_pay_ord_01_w	int
      |dd_cnt_wx_pay_ord_02_w	int
      |dd_cnt_wx_pay_ord_03_w	int
      |dd_cnt_wx_pay_ord_04_w	int
      |dd_cnt_wx_pay_ord_01_m	int
      |dd_cnt_wx_pay_ord_02_m	int
      |dd_cnt_wx_pay_ord_03_m	int
      |dd_cnt_wx_pay_ord_04_m	int
      |dd_cnt_wx_pay_ord_05_m	int
      |dd_cnt_wx_pay_ord_06_m	int
      |dd_cnt_wx_pay_use_bonus_ord_01_d	int
      |dd_cnt_wx_pay_use_bonus_ord_02_d	int
      |dd_cnt_wx_pay_use_bonus_ord_03_d	int
      |dd_cnt_wx_pay_use_bonus_ord_04_d	int
      |dd_cnt_wx_pay_use_bonus_ord_05_d	int
      |dd_cnt_wx_pay_use_bonus_ord_06_d	int
      |dd_cnt_wx_pay_use_bonus_ord_07_d	int
      |dd_cnt_wx_pay_use_bonus_ord_01_w	int
      |dd_cnt_wx_pay_use_bonus_ord_02_w	int
      |dd_cnt_wx_pay_use_bonus_ord_03_w	int
      |dd_cnt_wx_pay_use_bonus_ord_04_w	int
      |dd_cnt_wx_pay_use_bonus_ord_01_m	int
      |dd_cnt_wx_pay_use_bonus_ord_02_m	int
      |dd_cnt_wx_pay_use_bonus_ord_03_m	int
      |dd_cnt_wx_pay_use_bonus_ord_04_m	int
      |dd_cnt_wx_pay_use_bonus_ord_05_m	int
      |dd_cnt_wx_pay_use_bonus_ord_06_m	int
      |dd_cnt_wx_pay_nouse_bonus_ord_01_w	int
      |dd_cnt_wx_pay_nouse_bonus_ord_02_w	int
      |dd_cnt_wx_pay_nouse_bonus_ord_03_w	int
      |dd_cnt_wx_pay_nouse_bonus_ord_04_w	int
      |dd_cnt_wx_pay_nouse_bonus_ord_01_m	int
      |dd_cnt_wx_pay_nouse_bonus_ord_02_m	int
      |dd_cnt_wx_pay_nouse_bonus_ord_03_m	int
      |dd_cnt_wx_pay_nouse_bonus_ord_04_m	int
      |dd_cnt_wx_pay_nouse_bonus_ord_05_m	int
      |dd_cnt_wx_pay_nouse_bonus_ord_06_m	int
      |dd_cnt_wx_pay_nouse_bonus_ord_01_d	int
      |dd_cnt_wx_pay_nouse_bonus_ord_02_d	int
      |dd_cnt_wx_pay_nouse_bonus_ord_03_d	int
      |dd_cnt_wx_pay_nouse_bonus_ord_04_d	int
      |dd_cnt_wx_pay_nouse_bonus_ord_05_d	int
      |dd_cnt_wx_pay_nouse_bonus_ord_06_d	int
      |dd_cnt_wx_pay_nouse_bonus_ord_07_d	int
      |dd_amt_wx_use_bonus_01_d	double
      |dd_amt_wx_use_bonus_02_d	double
      |dd_amt_wx_use_bonus_03_d	double
      |dd_amt_wx_use_bonus_04_d	double
      |dd_amt_wx_use_bonus_05_d	double
      |dd_amt_wx_use_bonus_06_d	double
      |dd_amt_wx_use_bonus_07_d	double
      |dd_amt_wx_use_bonus_01_w	double
      |dd_amt_wx_use_bonus_02_w	double
      |dd_amt_wx_use_bonus_03_w	double
      |dd_amt_wx_use_bonus_04_w	double
      |dd_amt_wx_use_bonus_01_m	double
      |dd_amt_wx_use_bonus_02_m	double
      |dd_amt_wx_use_bonus_03_m	double
      |dd_amt_wx_use_bonus_04_m	double
      |dd_amt_wx_use_bonus_05_m	double
      |dd_amt_wx_use_bonus_06_m	double
      |dd_amt_wx_succ_pay_01_d	double
      |dd_amt_wx_succ_pay_02_d	double
      |dd_amt_wx_succ_pay_03_d	double
      |dd_amt_wx_succ_pay_04_d	double
      |dd_amt_wx_succ_pay_05_d	double
      |dd_amt_wx_succ_pay_06_d	double
      |dd_amt_wx_succ_pay_07_d	double
      |kd_amt_zc_pay_cost_01_d	double
      |kd_amt_zc_pay_cost_02_d	double
      |kd_amt_zc_pay_cost_03_d	double
      |kd_amt_zc_pay_cost_04_d	double
      |kd_amt_zc_pay_cost_05_d	double
      |kd_amt_zc_pay_cost_06_d	double
      |kd_amt_zc_pay_cost_07_d	double
      |kd_amt_kc_pay_cost_01_d	double
      |kd_amt_kc_pay_cost_02_d	double
      |kd_amt_kc_pay_cost_03_d	double
      |kd_amt_kc_pay_cost_04_d	double
      |kd_amt_kc_pay_cost_05_d	double
      |kd_amt_kc_pay_cost_06_d	double
      |kd_amt_kc_pay_cost_07_d	double
      |kd_amt_taxi_pay_cost_01_d	double
      |kd_amt_taxi_pay_cost_02_d	double
      |kd_amt_taxi_pay_cost_03_d	double
      |kd_amt_taxi_pay_cost_04_d	double
      |kd_amt_taxi_pay_cost_05_d	double
      |kd_amt_taxi_pay_cost_06_d	double
      |kd_amt_taxi_pay_cost_07_d	double
      |kd_amt_pay_cost_01_d	double
      |kd_amt_pay_cost_02_d	double
      |kd_amt_pay_cost_03_d	double
      |kd_amt_pay_cost_04_d	double
      |kd_amt_pay_cost_05_d	double
      |kd_amt_pay_cost_06_d	double
      |kd_amt_pay_cost_07_d	double
      |dd_amt_wx_succ_pay_01_w	double
      |dd_amt_wx_succ_pay_02_w	double
      |dd_amt_wx_succ_pay_03_w	double
      |dd_amt_wx_succ_pay_04_w	double
      |kd_amt_zc_pay_cost_01_w	double
      |kd_amt_zc_pay_cost_02_w	double
      |kd_amt_zc_pay_cost_03_w	double
      |kd_amt_zc_pay_cost_04_w	double
      |kd_amt_kc_pay_cost_01_w	double
      |kd_amt_kc_pay_cost_02_w	double
      |kd_amt_kc_pay_cost_03_w	double
      |kd_amt_kc_pay_cost_04_w	double
      |kd_amt_taxi_pay_cost_01_w	double
      |kd_amt_taxi_pay_cost_02_w	double
      |kd_amt_taxi_pay_cost_03_w	double
      |kd_amt_taxi_pay_cost_04_w	double
      |kd_amt_pay_cost_01_w	double
      |kd_amt_pay_cost_02_w	double
      |kd_amt_pay_cost_03_w	double
      |kd_amt_pay_cost_04_w	double
      |dd_amt_wx_succ_pay_01_m	double
      |dd_amt_wx_succ_pay_02_m	double
      |dd_amt_wx_succ_pay_03_m	double
      |dd_amt_wx_succ_pay_04_m	double
      |dd_amt_wx_succ_pay_05_m	double
      |dd_amt_wx_succ_pay_06_m	double
      |kd_amt_zc_pay_cost_01_m	double
      |kd_amt_zc_pay_cost_02_m	double
      |kd_amt_zc_pay_cost_03_m	double
      |kd_amt_zc_pay_cost_04_m	double
      |kd_amt_zc_pay_cost_05_m	double
      |kd_amt_zc_pay_cost_06_m	double
      |kd_amt_kc_pay_cost_01_m	double
      |kd_amt_kc_pay_cost_02_m	double
      |kd_amt_kc_pay_cost_03_m	double
      |kd_amt_kc_pay_cost_04_m	double
      |kd_amt_kc_pay_cost_05_m	double
      |kd_amt_kc_pay_cost_06_m	double
      |kd_amt_taxi_pay_cost_01_m	double
      |kd_amt_taxi_pay_cost_02_m	double
      |kd_amt_taxi_pay_cost_03_m	double
      |kd_amt_taxi_pay_cost_04_m	double
      |kd_amt_taxi_pay_cost_05_m	double
      |kd_amt_taxi_pay_cost_06_m	double
      |kd_amt_pay_cost_01_m	double
      |kd_amt_pay_cost_02_m	double
      |kd_amt_pay_cost_03_m	double
      |kd_amt_pay_cost_04_m	double
      |kd_amt_pay_cost_05_m	double
      |kd_amt_pay_cost_06_m	double
      |dd_cnt_kc_rd_ords_01_d	int
      |dd_cnt_kc_rd_ords_02_d	int
      |dd_cnt_kc_rd_ords_03_d	int
      |dd_cnt_kc_rd_ords_04_d	int
      |dd_cnt_kc_rd_ords_05_d	int
      |dd_cnt_kc_rd_ords_06_d	int
      |dd_cnt_kc_rd_ords_07_d	int
      |dd_cnt_zc_rd_ords_01_d	int
      |dd_cnt_zc_rd_ords_02_d	int
      |dd_cnt_zc_rd_ords_03_d	int
      |dd_cnt_zc_rd_ords_04_d	int
      |dd_cnt_zc_rd_ords_05_d	int
      |dd_cnt_zc_rd_ords_06_d	int
      |dd_cnt_zc_rd_ords_07_d	int
      |dd_cnt_zc_rd_ords_01_w	int
      |dd_cnt_zc_rd_ords_02_w	int
      |dd_cnt_zc_rd_ords_03_w	int
      |dd_cnt_zc_rd_ords_04_w	int
      |dd_cnt_zc_rd_ords_01_m	int
      |dd_cnt_zc_rd_ords_02_m	int
      |dd_cnt_zc_rd_ords_03_m	int
      |dd_cnt_zc_rd_ords_04_m	int
      |dd_cnt_zc_rd_ords_05_m	int
      |dd_cnt_zc_rd_ords_06_m	int
      |dd_cnt_kc_rd_ords_01_w	int
      |dd_cnt_kc_rd_ords_02_w	int
      |dd_cnt_kc_rd_ords_03_w	int
      |dd_cnt_kc_rd_ords_04_w	int
      |dd_cnt_kc_rd_ords_01_m	int
      |dd_cnt_kc_rd_ords_02_m	int
      |dd_cnt_kc_rd_ords_03_m	int
      |dd_cnt_kc_rd_ords_04_m	int
      |dd_cnt_kc_rd_ords_05_m	int
      |dd_cnt_kc_rd_ords_06_m	int
      |dd_cnt_kc_rd_ords_tot	int
      |dd_cnt_zc_rd_ords_tot	int
      |dd_amt_zc_coupon_spendpay_01_w	double
      |dd_amt_zc_coupon_spendpay_02_w	double
      |dd_amt_zc_coupon_spendpay_03_w	double
      |dd_amt_zc_coupon_spendpay_04_w	double
      |dd_amt_zc_coupon_spendpay_01_d	double
      |dd_amt_zc_coupon_spendpay_02_d	double
      |dd_amt_zc_coupon_spendpay_03_d	double
      |dd_amt_zc_coupon_spendpay_04_d	double
      |dd_amt_zc_coupon_spendpay_05_d	double
      |dd_amt_zc_coupon_spendpay_06_d	double
      |dd_amt_zc_coupon_spendpay_07_d	double
      |dd_amt_kc_coupon_spendpay_01_d	double
      |dd_amt_kc_coupon_spendpay_02_d	double
      |dd_amt_kc_coupon_spendpay_03_d	double
      |dd_amt_kc_coupon_spendpay_04_d	double
      |dd_amt_kc_coupon_spendpay_05_d	double
      |dd_amt_kc_coupon_spendpay_06_d	double
      |dd_amt_kc_coupon_spendpay_07_d	double
      |dd_amt_kc_coupon_spendpay_01_w	double
      |dd_amt_kc_coupon_spendpay_02_w	double
      |dd_amt_kc_coupon_spendpay_03_w	double
      |dd_amt_kc_coupon_spendpay_04_w	double
      |dd_amt_kc_coupon_spendpay_01_m	double
      |dd_amt_kc_coupon_spendpay_02_m	double
      |dd_amt_kc_coupon_spendpay_03_m	double
      |dd_amt_kc_coupon_spendpay_04_m	double
      |dd_amt_kc_coupon_spendpay_05_m	double
      |dd_amt_kc_coupon_spendpay_06_m	double
      |dd_amt_zc_coupon_spendpay_01_m	double
      |dd_amt_zc_coupon_spendpay_02_m	double
      |dd_amt_zc_coupon_spendpay_03_m	double
      |dd_amt_zc_coupon_spendpay_04_m	double
      |dd_amt_zc_coupon_spendpay_05_m	double
      |dd_amt_zc_coupon_spendpay_06_m	double
      |dd_cnt_kc_coupon_spendpay_tot	int
      |dd_cnt_zc_coupon_spendpay_tot	int
      |dd_amt_zc_payable_cost_01_d	double
      |dd_amt_zc_payable_cost_02_d	double
      |dd_amt_zc_payable_cost_03_d	double
      |dd_amt_zc_payable_cost_04_d	double
      |dd_amt_zc_payable_cost_05_d	double
      |dd_amt_zc_payable_cost_06_d	double
      |dd_amt_zc_payable_cost_07_d	double
      |dd_amt_zc_payable_cost_01_w	double
      |dd_amt_zc_payable_cost_02_w	double
      |dd_amt_zc_payable_cost_03_w	double
      |dd_amt_zc_payable_cost_04_w	double
      |dd_amt_zc_actual_cost_01_w	double
      |dd_amt_zc_actual_cost_02_w	double
      |dd_amt_zc_actual_cost_03_w	double
      |dd_amt_zc_actual_cost_04_w	double
      |dd_amt_zc_payable_cost_01_m	double
      |dd_amt_zc_payable_cost_02_m	double
      |dd_amt_zc_payable_cost_03_m	double
      |dd_amt_zc_payable_cost_04_m	double
      |dd_amt_zc_payable_cost_05_m	double
      |dd_amt_zc_payable_cost_06_m	double
      |dd_amt_kc_payable_cost_01_d	double
      |dd_amt_kc_payable_cost_02_d	double
      |dd_amt_kc_payable_cost_03_d	double
      |dd_amt_kc_payable_cost_04_d	double
      |dd_amt_kc_payable_cost_05_d	double
      |dd_amt_kc_payable_cost_06_d	double
      |dd_amt_kc_payable_cost_07_d	double
      |dd_amt_kc_payable_cost_01_w	double
      |dd_amt_kc_payable_cost_02_w	double
      |dd_amt_kc_payable_cost_03_w	double
      |dd_amt_kc_payable_cost_04_w	double
      |dd_amt_kc_payable_cost_01_m	double
      |dd_amt_kc_payable_cost_02_m	double
      |dd_amt_kc_payable_cost_03_m	double
      |dd_amt_kc_payable_cost_04_m	double
      |dd_amt_kc_payable_cost_05_m	double
      |dd_amt_kc_payable_cost_06_m	double
      |dd_amt_zc_payable_cost_tot	double
      |dd_amt_kc_payable_cost_tot	double
      |dd_amt_zc_actual_cost_01_d	double
      |dd_amt_zc_actual_cost_02_d	double
      |dd_amt_zc_actual_cost_03_d	double
      |dd_amt_zc_actual_cost_04_d	double
      |dd_amt_zc_actual_cost_05_d	double
      |dd_amt_zc_actual_cost_06_d	double
      |dd_amt_zc_actual_cost_07_d	double
      |dd_amt_zc_actual_cost_01_m	double
      |dd_amt_zc_actual_cost_02_m	double
      |dd_amt_zc_actual_cost_03_m	double
      |dd_amt_zc_actual_cost_04_m	double
      |dd_amt_zc_actual_cost_05_m	double
      |dd_amt_zc_actual_cost_06_m	double
      |dd_amt_kc_actual_cost_01_d	double
      |dd_amt_kc_actual_cost_02_d	double
      |dd_amt_kc_actual_cost_03_d	double
      |dd_amt_kc_actual_cost_04_d	double
      |dd_amt_kc_actual_cost_05_d	double
      |dd_amt_kc_actual_cost_06_d	double
      |dd_amt_kc_actual_cost_07_d	double
      |dd_amt_kc_actual_cost_01_w	double
      |dd_amt_kc_actual_cost_02_w	double
      |dd_amt_kc_actual_cost_03_w	double
      |dd_amt_kc_actual_cost_04_w	double
      |dd_amt_kc_actual_cost_01_m	double
      |dd_amt_kc_actual_cost_02_m	double
      |dd_amt_kc_actual_cost_03_m	double
      |dd_amt_kc_actual_cost_04_m	double
      |dd_amt_kc_actual_cost_05_m	double
      |dd_amt_kc_actual_cost_06_m	double
      |dd_amt_zc_actual_cost_tot	double
      |dd_amt_kc_actual_cost_tot	double
      |dd_date_tot_first_succ	int
      |dd_date_tot_last_succ	int
      |dd_date_dc_first_succ	int
      |dd_date_dc_last_succ	int
      |dd_date_zc_first_succ	int
      |dd_date_zc_last_succ	int
      |dd_date_kc_first_succ	int
      |dd_date_kc_last_succ	int
      |dd_date_qy_first_call	int
      |dd_date_qy_last_call	int
      |dd_date_qy_first_succ	int
      |dd_date_qy_last_succ	int
      |kd_date_tot_first_succ	int
      |kd_date_tot_last_succ	int
      |kd_date_dc_first_succ	int
      |kd_date_dc_last_succ	int
      |kd_date_zc_first_succ	int
      |kd_date_zc_last_succ	int
      |kd_date_kc_first_succ	int
      |kd_date_kc_last_succ	int
      |dd_cnt_ord_succ_didi_global	int
      |dd_cnt_ord_didi_global	int
      |dd_cnt_wx_have_bonus_didi_global	int
      |dd_cnt_ord_noresp_tot	int
      |dd_cnt_ord_acpt_tot	int
      |dd_cnt_ord_ariv_tot	int
      |dd_cnt_ord_pkup_tot	int
      |dd_cnt_ord_wait_tot	int
      |dd_cnt_ord_dele_tot	int
      |dd_cnt_wx_pay_ord_tot	int
      |dd_cnt_wx_pay_use_bonus_ord_tot	int
      |dd_cnt_wx_pay_nouse_bonus_ord_tot	int
      |dd_amt_wx_have_bonus_didi_global	double
      |dd_amt_wx_didi_global	double
      |dd_amt_wx_use_bonus_tot	double
      |dd_amt_wx_succ_pay_tot	double
      |dd_amt_zc_coupon_spendpay_tot	double
      |dd_amt_kc_coupon_spendpay_tot	double
      |kd_amt_tot_pay_cost	double
      |year	string
      |month	string
      |day	string
      |pidsn	string""".stripMargin
}
